-- Solomode 2025 first-post resources; external destinations were not opened.
PRAGMA foreign_keys=ON;
BEGIN IMMEDIATE;
CREATE TEMP TABLE sm_e(id PRIMARY KEY,title,wip,status);
CREATE TEMP TABLE sm_r(entry_id,url,role,form,label,context,PRIMARY KEY(entry_id,url));
INSERT INTO sm_e VALUES(552,'Florek & Florka','https://boardgamegeek.com/thread/3454362','observed');
INSERT INTO sm_e VALUES(553,'Enchanted Forest Solo Variant','https://boardgamegeek.com/thread/3406119','observed');
INSERT INTO sm_e VALUES(554,'Sabi','https://boardgamegeek.com/thread/3466096','observed');
INSERT INTO sm_e VALUES(555,'Humanoid Monsters Have Brains','https://boardgamegeek.com/thread/3471610','observed');
INSERT INTO sm_e VALUES(556,'War Against the Chtorr - Psionic Corps','https://boardgamegeek.com/thread/3471614','observed');
INSERT INTO sm_e VALUES(557,'Junk Punk','https://boardgamegeek.com/thread/3446309','observed');
INSERT INTO sm_e VALUES(558,'Unfinished Window','https://boardgamegeek.com/thread/3350683','observed');
INSERT INTO sm_e VALUES(559,'The Wily Widow','https://boardgamegeek.com/thread/3455165','observed');
INSERT INTO sm_e VALUES(560,'Solo Automa for Avignon','https://boardgamegeek.com/thread/3472563','observed');
INSERT INTO sm_e VALUES(561,'The Bus Conspiracy','https://boardgamegeek.com/thread/3445556','observed');
INSERT INTO sm_e VALUES(562,'Veteran Solo Mode','https://boardgamegeek.com/thread/3418473','observed');
INSERT INTO sm_e VALUES(563,'Midnight Racetrack','https://boardgamegeek.com/thread/3472592','observed');
INSERT INTO sm_e VALUES(564,'Lone Digger','https://boardgamegeek.com/thread/3474645','observed');
INSERT INTO sm_e VALUES(565,'Codenames Rush','https://boardgamegeek.com/thread/3475523','none_declared');
INSERT INTO sm_e VALUES(566,'boop. Solo Mode','https://boardgamegeek.com/thread/3478437','observed');
INSERT INTO sm_e VALUES(567,'Bot Families','https://boardgamegeek.com/thread/3480600','observed');
INSERT INTO sm_e VALUES(568,'Full Auto','https://boardgamegeek.com/thread/3483643','observed');
INSERT INTO sm_e VALUES(569,'Solisauron','https://boardgamegeek.com/thread/3486373','not_observable');
INSERT INTO sm_e VALUES(570,'b-AI-rista','https://boardgamegeek.com/thread/3490914','observed');
INSERT INTO sm_e VALUES(571,'Felipe I / Felipe II','https://boardgamegeek.com/thread/3490911','observed');
INSERT INTO sm_e VALUES(572,'Forest Link','https://boardgamegeek.com/thread/3496730','observed');
INSERT INTO sm_e VALUES(573,'Cathy','https://boardgamegeek.com/thread/3327279','observed');
INSERT INTO sm_e VALUES(574,'Malakar','https://boardgamegeek.com/thread/3398741','observed');
INSERT INTO sm_e VALUES(575,'Shrimpy','https://boardgamegeek.com/thread/3502388','observed');
INSERT INTO sm_e VALUES(576,'SUPERCAT','https://boardgamegeek.com/thread/3425290','observed');
INSERT INTO sm_e VALUES(577,'Unofficial Automa for Deep Regrets','https://boardgamegeek.com/thread/3503201','observed');
INSERT INTO sm_e VALUES(578,'Nemesis','https://boardgamegeek.com/thread/3504827','observed');
INSERT INTO sm_e VALUES(579,'Grandma & Grandpa','https://boardgamegeek.com/thread/3511290','observed');
INSERT INTO sm_e VALUES(580,'Unofficial Solo Mode & Campaign Mode','https://boardgamegeek.com/thread/3385154','observed');
INSERT INTO sm_e VALUES(581,'YRO Solo Campaign','https://boardgamegeek.com/thread/3422271','observed');
INSERT INTO sm_e VALUES(582,'Throne Alone','https://boardgamegeek.com/thread/3383061','observed');
INSERT INTO sm_e VALUES(583,'M. KloneUs','https://boardgamegeek.com/thread/3511300','observed');
INSERT INTO sm_e VALUES(584,'Pharaoh Code Solo Mode',NULL,'not_checked');
INSERT INTO sm_e VALUES(585,'Lord d''Automa','https://boardgamegeek.com/thread/3512047','observed');
INSERT INTO sm_e VALUES(586,'Splendor Solo Mode',NULL,'not_checked');
INSERT INTO sm_e VALUES(587,'Cavemono','https://boardgamegeek.com/thread/3344024','observed');
INSERT INTO sm_e VALUES(588,'Up Front Browser Automa','https://boardgamegeek.com/thread/3512452','observed');
INSERT INTO sm_e VALUES(589,'RuneBot','https://boardgamegeek.com/thread/3510981','observed');
INSERT INTO sm_r VALUES('552','https://steamcommunity.com/sharedfiles/filedetails/?id=2413052884','online_play','workshop_module','TTS','TTS indicato per provare il gioco base e la variante.');
INSERT INTO sm_r VALUES('552','https://boardgamegeek.com/filepage/296490/florek-and-florka-the-automas-artificial-opponents','rules','bgg_file','Download rulebook package (PDF + PNG)','Pacchetto PDF e PNG.');
INSERT INTO sm_r VALUES('553','https://docs.google.com/document/d/1GukDC9HkRbdkeLaCgFk1oCFbfyzk8R3w8LTv2G5_Mug/edit?usp=sharing','rules','document','Version 3','Versioni corrente e storiche.');
INSERT INTO sm_r VALUES('553','https://docs.google.com/document/d/1Cz-Dw_9B7_vCulIX0W8C718YP4K7yAexAshyqGlfYho/edit?usp=sharing','rules','document','version 2','Versioni corrente e storiche.');
INSERT INTO sm_r VALUES('553','https://docs.google.com/document/d/1P7NAZHlbUXtupoYEYxHaCMzmi4hzkTXmTPDBPI6Pg-I/edit?usp=sharing','rules','document','version 1','Versioni corrente e storiche.');
INSERT INTO sm_r VALUES('553','https://boardgamegeek.com/thread/3406119/article/45891618#45891618','rules','document','solo variant mockup','Versioni corrente e storiche.');
INSERT INTO sm_r VALUES('554','https://drive.google.com/file/d/11hhBp7RJ5toQAx_QSBG_ENMR800Az5F1/view?usp=sharing','rules','file','downloaded here','Regole PDF.');
INSERT INTO sm_r VALUES('555','https://boardgamegeek.com/filepage/296114/2025-solomode-contest-my-solo-mode-for-quest-for-t','game_files','bgg_file','rules and cards','Regole e carte.');
INSERT INTO sm_r VALUES('556','https://boardgamegeek.com/filepage/296126/2025-solomode-contest-my-solo-mode-for-warfighter','game_files','bgg_file','rules and cards','Regole e carte.');
INSERT INTO sm_r VALUES('557','https://boardgamegeek.com/filepage/317610/solo-mode-junk-punk','rules','bgg_file','solo automa','File dell’automa.');
INSERT INTO sm_r VALUES('558','https://docs.google.com/document/d/1NqXSTtlYbg_i6xLOpORzNijOClKOMCNJDpIOO2m_jFc/edit?usp=sharing','rules','document','version 4.1','Versioni delle regole.');
INSERT INTO sm_r VALUES('558','https://docs.google.com/document/d/1GD2aBYuZ0fEi6TWcp6tVan3z7s5DcxuxWfT4octg1fc/edit?usp=sharing','rules','document','version 1','Versioni delle regole.');
INSERT INTO sm_r VALUES('558','https://docs.google.com/document/d/1U4Jv94L4EcAx9aSBb5Gdlkoja9--yAfPO1Zu-Bfb7TY/edit?usp=sharing','rules','document','version 2','Versioni delle regole.');
INSERT INTO sm_r VALUES('558','https://docs.google.com/document/d/1-9q8z7xTF9Fn2rFIRYeV3WtpdTA_s6RCdfjTKrt3a_c/edit?usp=sharing','rules','document','version 3','Versioni delle regole.');
INSERT INTO sm_r VALUES('558','https://docs.google.com/document/d/1_HjdEkvOhbhxCuqzXuGvv756r-e9EnihqHGr18P1uKk/edit?usp=sharing','rules','document','version 4','Versioni delle regole.');
INSERT INTO sm_r VALUES('558','https://docs.google.com/document/d/1Sr0FBofNALlDa_P3O8Locv2SYomx8j0k/edit?usp=sharing&ouid=106836397923669534161&rtpof=true&sd=true','player_aid','document','player aid created by Anke','Aiuto giocatore.');
INSERT INTO sm_r VALUES('559','https://boardgamegeek.com/filepage/301437/the-wily-widow-a-deadly-dowagers-solomode','rules','bgg_file','Rules PDF','Regole.');
INSERT INTO sm_r VALUES('559','https://tabletopia.com/games/deadly-dowagers','online_play','web_app','Tabletopia','Piattaforme indicate per il playtest.');
INSERT INTO sm_r VALUES('559','https://steamcommunity.com/sharedfiles/filedetails/?id=3211478551','online_play','web_app','Tabletop Simulator','Piattaforme indicate per il playtest.');
INSERT INTO sm_r VALUES('559','https://youtube.com/watch?v=crRQPQILJ1s','video','video','Deadly Dowagers - In Focus','Video panoramica; canale automatico escluso.');
INSERT INTO sm_r VALUES('560','https://docs.google.com/document/d/1rTuHtpetJ5OFfJoWmXKl1h4EWRINy02f63ZAxgEOve8/edit?tab=t.0#heading=h.dwlaadsewinq','rules','document','Automa Rules','Regole correnti.');
INSERT INTO sm_r VALUES('561','https://talkingshelfspace.com/extras/','project_page','download_page','talkingshelfspace.com/extras','Pagina indicata per PDF e formattazione.');
INSERT INTO sm_r VALUES('562','https://talkingshelfspace.com/extras/','project_page','download_page','talkingshelfspace.com','Pagina indicata per la variante.');
INSERT INTO sm_r VALUES('563','https://drive.google.com/file/d/14bALQUgEPogJfBcQktP6zhksxoVH6Jnz/view?usp=sharing','rules','file','here','Regole PDF.');
INSERT INTO sm_r VALUES('564','https://docs.google.com/document/d/11lRF-IbilykUjsqydeUNkma6dvx9y_ArNW5R93FjfAc/edit?usp=sharing','rules','document','Google Drive','Regole.');
INSERT INTO sm_r VALUES('566','https://boardgamegeek.com/thread/3478437/article/45813015#45813015','rules','bgg_article','second revision','Seconda revisione nel thread.');
INSERT INTO sm_r VALUES('567','https://boardgamegeek.com/filepage/297062/du-plessis-de-winter-et-les-autres-familles-bot-fa','rules','bgg_file','bot families','Regole della variante.');
INSERT INTO sm_r VALUES('568','https://boardgamegeek.com/filepage/304242/joyride-full-auto-rules-for-self-driving-cars-allo','rules','bgg_file','most recent version','Versione 7A corrente.');
INSERT INTO sm_r VALUES('568','https://drive.google.com/file/d/1xdXJKOZiTLJJVyT1OBocTpM_HCX9FcuK/view?usp=sharing','rules','file','Version 7','Versioni Google Drive.');
INSERT INTO sm_r VALUES('568','https://drive.google.com/file/d/1cLGe0nRS1_xRLsypP3SnXeV1l-V7hMn6/view','rules','file','rules','Versioni Google Drive.');
INSERT INTO sm_r VALUES('568','https://youtube.com/watch?v=O1HNQfoTW94','video','video','How to Play JOYRIDE Solo','How-to-play.');
INSERT INTO sm_r VALUES('568','https://boardgamegeek.com/thread/3401491/solo-mode','supporting_page','bgg_thread','development thread','Discussione e resoconto.');
INSERT INTO sm_r VALUES('568','https://boardgamegeek.com/thread/3474388/solo-play-through-against-3-bots-using-the-full-au','supporting_page','bgg_thread','session report','Discussione e resoconto.');
INSERT INTO sm_r VALUES('570','https://boardgamegeek.com/filepage/297774/unofficial-solo-variant-coffee-rush-against-b-ai-r','game_files','bgg_file','rules and automa deck','Regole e mazzo automa.');
INSERT INTO sm_r VALUES('571','https://boardgamegeek.com/filepage/297776/unofficial-solo-va','game_files','bgg_file','files section','Href troncato conservato esattamente.');
INSERT INTO sm_r VALUES('572','https://drive.google.com/file/d/1i2K2-GTKHHpc6p609VY4ffJI9Zmgnz8G/view?usp=sharing','rules','file','Rules document','Regolamento.');
INSERT INTO sm_r VALUES('573','https://drive.google.com/drive/folders/18qVcYBCT6E_lvcNNp5bW_1CKP8lTB1uZ?usp=sharing','game_files','folder','Unofficial Solo Mode','Regole e mazzo solo.');
INSERT INTO sm_r VALUES('573','https://youtube.com/watch?v=Me0Qxohb-BY','video','video','How to play','How-to-play e playthrough; canali esclusi.');
INSERT INTO sm_r VALUES('573','https://youtube.com/watch?v=E8fmc2d99so','video','video','Playthrough','How-to-play e playthrough; canali esclusi.');
INSERT INTO sm_r VALUES('574','https://drive.google.com/drive/folders/1RCm_Ry4_4BjGlaMGgfEPE5FnhfZdNykK','game_files','folder','Unofficial Solo Mode','Regole e mazzo solo.');
INSERT INTO sm_r VALUES('574','https://youtube.com/watch?v=tlDbskiW9TU','video','video','How to play','How-to-play e playthrough; canali esclusi.');
INSERT INTO sm_r VALUES('574','https://youtube.com/watch?v=OamzD4SFUZQ','video','video','Playthrough','How-to-play e playthrough; canali esclusi.');
INSERT INTO sm_r VALUES('575','https://www.youtube.com/watch?v=jSfY3jeY278','video','video','how to play MANTIS','Video del gioco base dichiarato come supporto.');
INSERT INTO sm_r VALUES('575','https://boardgamegeek.com/filepage/299322/mantis-automa-shrimpy','rules','bgg_file','Download the PDF','Regole automa.');
INSERT INTO sm_r VALUES('576','https://github.com/okonomichiyaki/supercat/releases/download/v0.10/SUPERCAT-base-rules.pdf','game_files','file','latest version v0.10','Regole e aiuti sperimentali.');
INSERT INTO sm_r VALUES('576','https://github.com/okonomichiyaki/supercat/releases/download/v0.10/SUPERCAT-base-player-aid.pdf','game_files','file','experimental player aid','Regole e aiuti sperimentali.');
INSERT INTO sm_r VALUES('576','https://github.com/okonomichiyaki/supercat/releases/download/v0.10/SUPERCAT-base-action-cards.pdf','game_files','file','experimental action card deck','Regole e aiuti sperimentali.');
INSERT INTO sm_r VALUES('576','https://boardgamegeek.com/thread/3425290/article/46008535#46008535','supporting_page','bgg_article','player aid instructions','Istruzioni e discussione.');
INSERT INTO sm_r VALUES('576','https://boardgamegeek.com/thread/3425290/article/46121480#46121480','supporting_page','bgg_article','action card instructions','Istruzioni e discussione.');
INSERT INTO sm_r VALUES('576','https://boardgamegeek.com/thread/3499164/supercat-a-procedural-non-player-system-for-solo-b','supporting_page','bgg_article','supporting thread','Istruzioni e discussione.');
INSERT INTO sm_r VALUES('577','https://boardgamegeek.com/filepage/298450/unofficial-automa-for-deep-regrets','rules','bgg_file','version 2.1','Regole della variante.');
INSERT INTO sm_r VALUES('578','https://boardgamegeek.com/filepage/299328/nemesis-elysium-solobot','rules','bgg_file','Link to the PDF','Regole della variante.');
INSERT INTO sm_r VALUES('579','https://boardgamegeek.com/filepage/296317/unofficial-solo-variant','rules','bgg_file','Unofficial Solo Variant','Regole della variante.');
INSERT INTO sm_r VALUES('580','https://boardgamegeek.com/filepage/287495/unofficial-solo-mode-and-campaign-v10','rules','bgg_file','V.1.0','Regole della variante.');
INSERT INTO sm_r VALUES('581','https://boardgamegeek.com/filepage/291216','rules','bgg_file','English Version','Versioni inglese e tedesca.');
INSERT INTO sm_r VALUES('581','https://boardgamegeek.com/filepage/291217','rules','bgg_file','German Version','Versioni inglese e tedesca.');
INSERT INTO sm_r VALUES('582','https://boardgamegeek.com/filepage/301489/castle-combo-throne-alone-solo-mode-rules','rules','bgg_file','file section','Regole.');
INSERT INTO sm_r VALUES('582','https://youtu.be/XQ78uuQ-Bfo','video','video','German playthrough','Playthrough inglese e tedesco.');
INSERT INTO sm_r VALUES('582','https://youtu.be/YrZLSaKWFhc','video','video','English playthrough','Playthrough inglese e tedesco.');
INSERT INTO sm_r VALUES('583','https://boardgamegeek.com/filepage/300400/2025-solomode-m-kloneus','rules','bgg_file','PDF','PDF.');
INSERT INTO sm_r VALUES('585','https://docs.google.com/document/d/1u0cRjgeagJr1cFnBHGmt9Fl2rz1qJPtjqvoi-2EQJlY/edit?usp=sharing','rules','document','Full rules here','Regole.');
INSERT INTO sm_r VALUES('587','https://drive.google.com/file/d/1OAd1-nuHZLVXWjAz-MGRueD9Pe37fBbp/view?usp=drive_link','component','file','PnP Cards v0.1','Carte PnP.');
INSERT INTO sm_r VALUES('587','https://drive.google.com/file/d/1NSSRRBLpG68LvIpalyL8U16FB8nPNPNf/view?usp=drive_link','rules','file','Rulebook v0.2','Regolamento.');
INSERT INTO sm_r VALUES('588','https://github.com/bsturk/up_front_bot','online_tool','source_repository','up_front_bot','Repository dell’applet browser.');
INSERT INTO sm_r VALUES('589','https://drive.google.com/drive/folders/1LD-mUpN6VArPUGob20eEGmwLBxdmJbLi?usp=sharing','game_files','folder','rules file and two card sheets','Regole e due fogli carte.');
INSERT INTO sm_r VALUES('589','https://drive.google.com/file/d/1e7vekARsFQVj3wV53OFNOxGsHH_sA3MV/view?usp=sharing','audio','file','podcast overview','Panoramica podcast.');
INSERT INTO sm_r VALUES('589','https://docs.google.com/document/d/1TkmzgoSoo09hn0Q0r6l59iAwPMhHIChO/edit?usp=drivesdk&ouid=116225575084141017501&rtpof=true&sd=true','rules','document','Original 8 card bot','Versione originale a otto carte.');
UPDATE entries SET wip_thread_url=(SELECT wip FROM sm_e WHERE sm_e.id=entries.id) WHERE contest_id=16;
DELETE FROM entry_resource_scans WHERE entry_id IN (SELECT id FROM entries WHERE contest_id=16) AND checked_at='2026-09-15';
INSERT INTO entry_resource_scans(entry_id,checked_at,source_url,wip_status,resource_listing_status,notes) SELECT id,'2026-09-15',COALESCE(wip,'https://boardgamegeek.com/geeklist/353866/2025-solomode-design-contest-submissions'),CASE WHEN wip IS NULL THEN 'not_found' ELSE 'found' END,status,CASE WHEN status='not_observable' THEN 'Risorsa dichiarata ma non più osservabile dal primo post.' WHEN status='not_checked' THEN 'La voce GeekList punta alla pagina generale del contest; nessun WIP individuale inventato.' WHEN status='none_declared' THEN 'Primo post letto integralmente: nessun collegamento pertinente osservato.' ELSE 'Primo post renderizzato censito; destinazioni non aperte.' END FROM sm_e;
INSERT OR IGNORE INTO remote_resources(game_id,kind,access_type,url,host,label,availability_status,first_seen_at,last_verified_at) SELECT e.game_id,r.role,r.form,r.url,substr(r.url,instr(r.url,'//')+2,instr(substr(r.url,instr(r.url,'//')+2),'/')-1),r.label,'unknown','2026-09-15','2026-09-15' FROM sm_r r JOIN entries e ON e.id=r.entry_id;
DELETE FROM entry_resource_mentions WHERE entry_id IN (SELECT id FROM entries WHERE contest_id=16);
INSERT INTO entry_resource_mentions(entry_id,remote_resource_id,source_url,label_raw,content_role,is_primary,first_seen_at,last_seen_at) SELECT r.entry_id,rr.id,s.wip,r.label,r.role,CASE WHEN r.role='game_files' THEN 1 ELSE 0 END,'2026-09-15','2026-09-15' FROM sm_r r JOIN sm_e s ON s.id=r.entry_id JOIN entries e ON e.id=r.entry_id JOIN remote_resources rr ON rr.game_id=e.game_id AND rr.url=r.url;
INSERT INTO remote_resource_observations(remote_resource_id,observed_at,evidence_url,observation_kind,availability_status,notes) SELECT rr.id,'2026-09-15',s.wip,'declared_in_wip','not_checked','Destinazione non aperta. Contesto: '||r.context FROM sm_r r JOIN sm_e s ON s.id=r.entry_id JOIN entries e ON e.id=r.entry_id JOIN remote_resources rr ON rr.game_id=e.game_id AND rr.url=r.url WHERE NOT EXISTS(SELECT 1 FROM remote_resource_observations o WHERE o.remote_resource_id=rr.id AND o.observed_at='2026-09-15');
INSERT OR IGNORE INTO entry_resource_mentions(entry_id,remote_resource_id,source_url,label_raw,content_role,is_primary,first_seen_at,last_seen_at) SELECT e.id,rr.id,e.wip_thread_url,rr.label,rr.kind,CASE WHEN rr.kind='game_files' THEN 1 ELSE 0 END,'2026-09-15','2026-09-15' FROM entries e JOIN remote_resources rr ON rr.game_id=e.game_id WHERE e.contest_id=16 AND rr.first_seen_at='2026-09-15';
INSERT INTO remote_resource_observations(remote_resource_id,observed_at,evidence_url,observation_kind,availability_status,notes) SELECT rr.id,'2026-09-15',e.wip_thread_url,'declared_in_wip','not_checked','Destinazione non aperta. Contesto: '||COALESCE((SELECT r.context FROM sm_r r WHERE r.entry_id=e.id AND r.url=rr.url),'vedere registro versionato') FROM entries e JOIN remote_resources rr ON rr.game_id=e.game_id WHERE e.contest_id=16 AND rr.first_seen_at='2026-09-15' AND NOT EXISTS(SELECT 1 FROM remote_resource_observations o WHERE o.remote_resource_id=rr.id AND o.observed_at='2026-09-15');
DROP TABLE sm_r;
DROP TABLE sm_e;
COMMIT;
