-- Full first-post resource census for 2025 Children & Family. External destinations were not opened.
PRAGMA foreign_keys = ON;
BEGIN IMMEDIATE;
CREATE TEMP TABLE cf_entry(entry_id INTEGER PRIMARY KEY,title TEXT NOT NULL,wip_url TEXT,listing_status TEXT NOT NULL);
CREATE TEMP TABLE cf_resource(entry_id INTEGER,url TEXT,role TEXT,access_type TEXT,label TEXT,context TEXT,PRIMARY KEY(entry_id,url));
INSERT INTO cf_entry VALUES(487,'Good Breeding','https://boardgamegeek.com/thread/3431880','observed');
INSERT INTO cf_entry VALUES(488,'Pirate Treasures','https://boardgamegeek.com/thread/3435409','none_declared');
INSERT INTO cf_entry VALUES(489,'Pets Rescue','https://boardgamegeek.com/thread/3441653','none_declared');
INSERT INTO cf_entry VALUES(490,'Swirls','https://boardgamegeek.com/thread/3387063','observed');
INSERT INTO cf_entry VALUES(491,'The Robots are Multiplying','https://boardgamegeek.com/thread/3442172','observed');
INSERT INTO cf_entry VALUES(492,'Potions Master Tournament',NULL,'not_checked');
INSERT INTO cf_entry VALUES(493,'Isles of Odd','https://boardgamegeek.com/thread/3441309','observed');
INSERT INTO cf_entry VALUES(494,'Peng Wins!','https://boardgamegeek.com/thread/3449433','observed');
INSERT INTO cf_entry VALUES(495,'Hex Hive: Skirmish','https://boardgamegeek.com/thread/3449448','none_declared');
INSERT INTO cf_entry VALUES(496,'Slowpoke','https://boardgamegeek.com/thread/3451616','observed');
INSERT INTO cf_entry VALUES(497,'Origami Champions','https://boardgamegeek.com/thread/3451743','observed');
INSERT INTO cf_entry VALUES(498,'Sorry! That''s My Dungeon','https://boardgamegeek.com/thread/3442526','observed');
INSERT INTO cf_entry VALUES(499,'Ice Cream Heist','https://boardgamegeek.com/thread/3462311','observed');
INSERT INTO cf_entry VALUES(500,'Poker Face','https://boardgamegeek.com/thread/3465191','observed');
INSERT INTO cf_entry VALUES(501,'Squirelly','https://boardgamegeek.com/thread/3465485','observed');
INSERT INTO cf_entry VALUES(502,'Head In The Clouds','https://boardgamegeek.com/thread/3469238','none_declared');
INSERT INTO cf_entry VALUES(503,'Submarine Adventure','https://boardgamegeek.com/thread/3473660','observed');
INSERT INTO cf_entry VALUES(504,'Island of Peril','https://boardgamegeek.com/thread/3482193','observed');
INSERT INTO cf_entry VALUES(505,'Mermaids vs Dinosaurs','https://boardgamegeek.com/thread/3484120','observed');
INSERT INTO cf_entry VALUES(506,'Allmende','https://boardgamegeek.com/thread/3487174','observed');
INSERT INTO cf_entry VALUES(507,'ICBRG','https://boardgamegeek.com/thread/3493395','observed');
INSERT INTO cf_entry VALUES(508,'Bon-Bon','https://boardgamegeek.com/thread/3493740','observed');
INSERT INTO cf_entry VALUES(509,'Zoo Rush','https://boardgamegeek.com/thread/3495361','observed');
INSERT INTO cf_entry VALUES(510,'Crab Boil','https://boardgamegeek.com/thread/3495781','observed');
INSERT INTO cf_entry VALUES(511,'Panic Picasso!','https://boardgamegeek.com/thread/3496634','observed');
INSERT INTO cf_entry VALUES(512,'Guesstrictions','https://boardgamegeek.com/thread/3496460','none_declared');
INSERT INTO cf_entry VALUES(513,'Amusement park - Clashes','https://boardgamegeek.com/thread/3496296','observed');
INSERT INTO cf_resource VALUES('487','https://drive.google.com/drive/folders/1HTjtBloUic_1z3ZxLjHZXqyQN0RItHW0','game_files','folder','CLICK HERE FOR LINK TO COMPONENTS','Folder dichiarata per componenti, tessere punteggio e regolamento.');
INSERT INTO cf_resource VALUES('487','https://youtube.com/watch?v=nyD5Lf5yK4I','video','video','Good Breeding','Video incorporato del gioco; canale YouTube automatico escluso.');
INSERT INTO cf_resource VALUES('490','https://boardgamegeek.com/thread/3388261/official-game-presentation-plus-pnp-files-plus-lin','project_page','download_page','PnP files + Links','Thread BGG dichiarato come pagina di presentazione, file PnP e collegamenti.');
INSERT INTO cf_resource VALUES('491','https://drive.google.com/drive/folders/1U-jwn9MmxArfXS0AIxniqI4YrvODVSMI?usp=sharing','game_files','folder','game files','Cartella dei file di gioco.');
INSERT INTO cf_resource VALUES('491','https://steamcommunity.com/sharedfiles/filedetails/?id=3414780892','online_play','workshop_module','Robots are MULTIPLYING on TTS','Modulo Tabletop Simulator.');
INSERT INTO cf_resource VALUES('493','https://www.canva.com/design/DAGTfqleqFM/SxYu95Fk4CYd4ysiaIp4XA/view?utm_content=DAGTfqleqFM&utm_campaign=designshare&utm_medium=link2&utm_source=uniquelinks&utlId=h0bb8437dcc','rules','document','RULEBOOK','Regolamento dichiarato nel primo post.');
INSERT INTO cf_resource VALUES('493','https://www.youtube.com/watch?v=btrWcvyDdd4','video','video','RULES VIDEO!','Video delle regole.');
INSERT INTO cf_resource VALUES('493','https://drive.google.com/drive/folders/1kAb6ps0BxrFo8lwEMrDMmSPUiw0DQAHU?usp=drive_link','game_files','folder','PRINT AND PLAY!','Cartella Print and Play.');
INSERT INTO cf_resource VALUES('493','https://steamcommunity.com/sharedfiles/filedetails/?id=3383183358','online_play','workshop_module','TABLETOP SIMULATOR!','Modulo Tabletop Simulator.');
INSERT INTO cf_resource VALUES('494','https://drive.google.com/file/d/1bRMFKYviShqv89N87QyNnt7lRdQ-8W-_/view?usp=sharing','game_files','file','[Components and Rules]','File unico dichiarato per componenti e regolamento.');
INSERT INTO cf_resource VALUES('496','https://linktr.ee/slowpokegame','project_page','download_page','https://linktr.ee/slowpokegame','Pagina aggregatrice del gioco.');
INSERT INTO cf_resource VALUES('496','https://docs.google.com/document/d/1_FmmwcxoPLaWpXbDO3aYw6E3HKSgiaE9sLTw3y7LcEg/edit?usp=sharing','rules','document','https://docs.google.com/document/d/1_FmmwcxoPLaWpXbDO3aYw6E3...','Regolamento Google document.');
INSERT INTO cf_resource VALUES('496','https://drive.google.com/file/d/12AXUphcMbo-hvtUcZoINTq5XCzDWC_jR/view?usp=sharing','game_files','file','https://drive.google.com/file/d/12AXUphcMbo-hvtUcZoINTq5XCzD...','File di gioco.');
INSERT INTO cf_resource VALUES('497','https://romab.itch.io/origami-champions/download/svnyZKTYODY1ygzXw1qLZ4zbdh_2TgcJTYMd8bG6','game_files','download_page','DOWNLOAD','Download Itch.io dichiarato nel primo post.');
INSERT INTO cf_resource VALUES('498','https://alexandrecamargo.itch.io/sorry-thats-my-dungeon','game_files','download_page','https://alexandrecamargo.itch.io/sorry-thats-my-dungeon','Pagina Itch.io dei file Print and Play.');
INSERT INTO cf_resource VALUES('499','https://drive.google.com/drive/folders/1wwt9avcEXb89YQdJImyHXqvnaXqg_IY7?usp=drive_link','game_files','folder','https://drive.google.com/drive/folders/1wwt9avcEXb89YQdJImyH...','Cartella dei materiali del gioco.');
INSERT INTO cf_resource VALUES('500','https://drive.google.com/file/d/1Qj7zr1IJVQeR8zsvkRhlZzry5e5QA1ZU/view?usp=drive_link','component','file','Ver. 0.1 Cards','Carte versione 0.1.');
INSERT INTO cf_resource VALUES('500','https://drive.google.com/file/d/1wTMUUwAJsTuvdoPhRyUFv3uhjf1Z0kCW/view?usp=drive_link','rules','file','Ver. 0.1 Rulebook','Regolamento versione 0.1.');
INSERT INTO cf_resource VALUES('501','https://drive.google.com/drive/folders/1LGdbkZj3mrqKiAkhXjFldlG6tCJZueF4?usp=sharing','game_files','folder','Here!','Cartella Google Drive dei file correnti.');
INSERT INTO cf_resource VALUES('501','https://steamcommunity.com/sharedfiles/filedetails/?id=3431578623','online_play','workshop_module','here!','Playtest digitale su Tabletop Simulator.');
INSERT INTO cf_resource VALUES('503','https://drive.google.com/file/d/1lZPFrQDFS3If4WwXilJzEGLMyvP-zb1l/view?usp=sharing','rules','file','[Rules]','Regolamento.');
INSERT INTO cf_resource VALUES('503','https://drive.google.com/file/d/1dw99YPj1fTMPgv0goPQhog1k4cEREwVS/view?usp=sharing','component','file','[Components]','Componenti.');
INSERT INTO cf_resource VALUES('503','https://steamcommunity.com/sharedfiles/filedetails/?id=3440131938','online_play','workshop_module','[Tabletop Simulator Mod]','Modulo Tabletop Simulator.');
INSERT INTO cf_resource VALUES('504','https://drive.google.com/drive/folders/1XhMiXjWg6244O21QTQN7mFfk9fTTP_a7?usp=sharing','game_files','folder','Google drive','Cartella di download del gioco.');
INSERT INTO cf_resource VALUES('505','https://drive.google.com/drive/folders/1zGPcGn3RqjxIoeSYFUSMms_lsTHQpeHH?usp=sharing','game_files','folder','Game Files','Cartella dei file di gioco.');
INSERT INTO cf_resource VALUES('505','https://docs.google.com/document/d/1c6fbzo61Ytm4uhcFQ5e6CdDhjreeG6WAw2qWq7-C8dI/edit?usp=sharing','rules','document','Rulebook Draft Doc','Bozza del regolamento.');
INSERT INTO cf_resource VALUES('505','https://steamcommunity.com/sharedfiles/filedetails/?id=3451271982','online_play','workshop_module','TTS Module','Modulo Tabletop Simulator.');
INSERT INTO cf_resource VALUES('505','https://youtube.com/watch?v=rn8Ua0MW_KE','video','video','How to play Mermaids vs Dinosaur','Video incorporato how-to-play; canale automatico escluso.');
INSERT INTO cf_resource VALUES('506','https://drive.google.com/drive/folders/https://drive.google.com/drive/folders/1SPvqNnKXTlV3Y3YI04zA-Ydpmwyr4ied?usp=sharing','game_files','folder','Download from google drive','URL Google Drive conservato esattamente come dichiarato; forma sintattica anomala non verificata.');
INSERT INTO cf_resource VALUES('506','https://steamcommunity.com/sharedfiles/filedetails/?id=3456867447','online_play','workshop_module','Tabletop Simulator','Modulo Tabletop Simulator.');
INSERT INTO cf_resource VALUES('506','https://www.youtube.com/watch?v=3n7VVfHGXL4','video','video','on Youtube','Manuale digitale su YouTube; riferimento incorporato duplicato accorpato.');
INSERT INTO cf_resource VALUES('507','https://drive.google.com/file/d/1fFHUf2LiuHYpH2lDG6UcTZpLU1Egykug/view?usp=drive_link','component','file','ICBRG PnP Version 2.1 (Last updated 4/30/25)','PnP versione 2.1.');
INSERT INTO cf_resource VALUES('507','https://drive.google.com/file/d/1E39KA-RsPZHBL4yOfBh_KBopZC0VEfJB/view?usp=drive_link','rules','file','ICBRG Rulebook Version 2.0 (Last updated 4/30/25)','Regolamento versione 2.0.');
INSERT INTO cf_resource VALUES('508','https://rollingolem.wordpress.com/197-2/','game_files','download_page','game files','Pagina dichiarata per regole e componenti PnP.');
INSERT INTO cf_resource VALUES('508','https://tabletopia.com/games/bonbon','online_play','web_app','tabletopia','Versione digitale su Tabletopia.');
INSERT INTO cf_resource VALUES('509','https://c.gmx.net/@327464636691519389/YOeFrQLGl7b_8fshNOMquA','game_files','file','Download color version','PDF a colori con regole e componenti.');
INSERT INTO cf_resource VALUES('509','https://c.gmx.net/@327464636691519389/codVtkSgl0lg96tFnH0QmA','game_files','file','Download printer-friendly (grayscale) version','PDF in scala di grigi con regole e componenti.');
INSERT INTO cf_resource VALUES('510','https://scobblehog-press.itch.io/crab-boil-a-print-play-crab-battle-boardgame','game_files','download_page','Itch.io Crab Boil Link','Pagina Itch.io del Print and Play.');
INSERT INTO cf_resource VALUES('511','https://drive.google.com/file/d/1HHJbCYuzNm1oHWrc4CWZ5TujdowJ-J5A/view?usp=drive_link','component','file','Prompt Cards and Points Tokens','Carte prompt e gettoni punti.');
INSERT INTO cf_resource VALUES('511','https://drive.google.com/file/d/1TGqPBrOt_SQp5kUGPQTyePEWfowrfh4j/view?usp=drive_link','rules','file','2 Page Rule book','Regolamento di due pagine.');
INSERT INTO cf_resource VALUES('513','https://docs.google.com/document/d/1hEfypoqizHyDm_A7EMcFqt48qQaH1PgfhrYPjpGJ_x4/edit?usp=sharing','rules','document','https://docs.google.com/document/d/1hEfypoqizHyDm_A7EMcFqt48...','Regolamento Google document.');
INSERT INTO cf_resource VALUES('513','https://drive.google.com/drive/folders/1GZelx-0nKt2PlI8JFyRhgWWSj0D03oB5?usp=sharing','game_files','folder','https://drive.google.com/drive/folders/1GZelx-0nKt2PlI8JFyRh...','Cartella dei componenti.');
INSERT INTO cf_resource VALUES('513','https://steamcommunity.com/sharedfiles/filedetails/?id=3464395035&result=8','online_play','workshop_module','https://steamcommunity.com/sharedfiles/filedetails/?id=34643...','Modulo Tabletop Simulator.');
UPDATE entries SET wip_thread_url=(SELECT wip_url FROM cf_entry i WHERE i.entry_id=entries.id) WHERE contest_id=14;
DELETE FROM entry_resource_scans WHERE checked_at='2026-09-11' AND entry_id IN (SELECT id FROM entries WHERE contest_id=14);
INSERT INTO entry_resource_scans(entry_id,checked_at,source_url,wip_status,resource_listing_status,notes) SELECT entry_id,'2026-09-11',COALESCE(wip_url,'https://boardgamegeek.com/geeklist/351008/2025-children-and-family-game-design-contest'),CASE WHEN wip_url IS NULL THEN 'not_found' ELSE 'found' END,listing_status,CASE listing_status WHEN 'observed' THEN 'Primo post renderizzato: anchor, link dinamici e media incorporati censiti; destinazioni non aperte.' WHEN 'none_declared' THEN 'Primo post renderizzato integralmente: nessun collegamento pertinente dichiarato osservato.' ELSE 'La voce GeekList espone risorse ma nessun WIP: risorse della lista non attribuite al censimento WIP.' END FROM cf_entry;
INSERT OR IGNORE INTO remote_resources(game_id,kind,access_type,url,host,label,version_raw,availability_status,first_seen_at,last_verified_at) SELECT e.game_id,r.role,r.access_type,r.url,CASE WHEN instr(substr(r.url,instr(r.url,'//')+2),'/')>0 THEN substr(substr(r.url,instr(r.url,'//')+2),1,instr(substr(r.url,instr(r.url,'//')+2),'/')-1) ELSE substr(r.url,instr(r.url,'//')+2) END,r.label,NULL,'unknown','2026-09-11','2026-09-11' FROM cf_resource r JOIN entries e ON e.id=r.entry_id;
UPDATE remote_resources SET kind=(SELECT r.role FROM cf_resource r JOIN entries e ON e.id=r.entry_id WHERE e.game_id=remote_resources.game_id AND r.url=remote_resources.url),access_type=(SELECT r.access_type FROM cf_resource r JOIN entries e ON e.id=r.entry_id WHERE e.game_id=remote_resources.game_id AND r.url=remote_resources.url),label=(SELECT r.label FROM cf_resource r JOIN entries e ON e.id=r.entry_id WHERE e.game_id=remote_resources.game_id AND r.url=remote_resources.url),last_verified_at='2026-09-11' WHERE EXISTS(SELECT 1 FROM cf_resource r JOIN entries e ON e.id=r.entry_id WHERE e.game_id=remote_resources.game_id AND r.url=remote_resources.url);
DELETE FROM entry_resource_mentions WHERE entry_id IN (SELECT id FROM entries WHERE contest_id=14);
INSERT INTO entry_resource_mentions(entry_id,remote_resource_id,source_url,label_raw,content_role,is_primary,first_seen_at,last_seen_at) SELECT r.entry_id,rr.id,i.wip_url,r.label,r.role,CASE WHEN r.role='game_files' THEN 1 ELSE 0 END,'2026-09-11','2026-09-11' FROM cf_resource r JOIN cf_entry i ON i.entry_id=r.entry_id JOIN entries e ON e.id=r.entry_id JOIN remote_resources rr ON rr.game_id=e.game_id AND rr.url=r.url;
INSERT INTO remote_resource_observations(remote_resource_id,observed_at,evidence_url,observation_kind,availability_status,version_raw,notes) SELECT rr.id,'2026-09-11',i.wip_url,'declared_in_wip','not_checked',NULL,'Dichiarata nel primo post BGG; destinazione non aperta. Contesto: '||r.context||' Classificazione funzionale e tecnica provvisoria fino alla revisione completa del 2025.' FROM cf_resource r JOIN cf_entry i ON i.entry_id=r.entry_id JOIN entries e ON e.id=r.entry_id JOIN remote_resources rr ON rr.game_id=e.game_id AND rr.url=r.url WHERE NOT EXISTS(SELECT 1 FROM remote_resource_observations o WHERE o.remote_resource_id=rr.id AND o.observed_at='2026-09-11' AND o.evidence_url=i.wip_url AND o.observation_kind='declared_in_wip');
DROP TABLE cf_resource;
DROP TABLE cf_entry;
COMMIT;
