-- Full first-post resource census for 2025 1-Card. External destinations were not opened.
PRAGMA foreign_keys=ON;
BEGIN IMMEDIATE;
CREATE TEMP TABLE oc_entry(entry_id INTEGER PRIMARY KEY,title TEXT,wip_url TEXT,listing_status TEXT);
CREATE TEMP TABLE oc_resource(entry_id INTEGER,url TEXT,role TEXT,access_type TEXT,label TEXT,context TEXT,PRIMARY KEY(entry_id,url));
INSERT INTO oc_entry VALUES(514,'Archipelago Rebels','https://boardgamegeek.com/thread/3505950','observed');
INSERT INTO oc_entry VALUES(515,'BEEP','https://boardgamegeek.com/thread/3508169','observed');
INSERT INTO oc_entry VALUES(516,'Boom!','https://boardgamegeek.com/thread/3501760','observed');
INSERT INTO oc_entry VALUES(517,'Breathless Tango','https://boardgamegeek.com/thread/3495445','observed');
INSERT INTO oc_entry VALUES(518,'Cuéntame (Tell me)','https://boardgamegeek.com/thread/3505085','observed');
INSERT INTO oc_entry VALUES(519,'Deceive to Succeed','https://boardgamegeek.com/thread/3491405','observed');
INSERT INTO oc_entry VALUES(520,'Delivery Dash','https://boardgamegeek.com/thread/3494616','observed');
INSERT INTO oc_entry VALUES(521,'Disturbance at Darkholm Manor','https://boardgamegeek.com/thread/3520521','not_observable');
INSERT INTO oc_entry VALUES(522,'Don’t Get Snaked!','https://boardgamegeek.com/thread/3487751','observed');
INSERT INTO oc_entry VALUES(523,'Finger Twister','https://boardgamegeek.com/thread/3516506','observed');
INSERT INTO oc_entry VALUES(524,'Flip Fart','https://boardgamegeek.com/thread/3515359','observed');
INSERT INTO oc_entry VALUES(525,'Going the Difference!','https://boardgamegeek.com/thread/3509254','observed');
INSERT INTO oc_entry VALUES(526,'Honeybee and Dragonfly','https://boardgamegeek.com/thread/3491504','observed');
INSERT INTO oc_entry VALUES(527,'Hovercraft in a Minefield: Alligator Rescue','https://boardgamegeek.com/thread/3510163','observed');
INSERT INTO oc_entry VALUES(528,'In the Trench','https://boardgamegeek.com/thread/3495777','observed');
INSERT INTO oc_entry VALUES(529,'Know B4 U Go','https://boardgamegeek.com/thread/3520264','observed');
INSERT INTO oc_entry VALUES(530,'Laced Up','https://boardgamegeek.com/thread/3509555','observed');
INSERT INTO oc_entry VALUES(531,'Locky Dice','https://boardgamegeek.com/thread/3495217','observed');
INSERT INTO oc_entry VALUES(532,'Lucky Words','https://boardgamegeek.com/thread/3491766','observed');
INSERT INTO oc_entry VALUES(533,'Matching Socks','https://boardgamegeek.com/thread/3494402','observed');
INSERT INTO oc_entry VALUES(534,'The Moving Fortress','https://boardgamegeek.com/thread/3489442','none_declared');
INSERT INTO oc_entry VALUES(535,'Nap & Roll','https://boardgamegeek.com/thread/3440820','observed');
INSERT INTO oc_entry VALUES(536,'One Card Battle','https://boardgamegeek.com/thread/3512843','observed');
INSERT INTO oc_entry VALUES(537,'One Card Guard','https://boardgamegeek.com/thread/3489141','observed');
INSERT INTO oc_entry VALUES(538,'One Intersection','https://boardgamegeek.com/thread/3511086','observed');
INSERT INTO oc_entry VALUES(539,'Pass the Dice','https://boardgamegeek.com/thread/3493787','observed');
INSERT INTO oc_entry VALUES(540,'The Peak','https://boardgamegeek.com/thread/3512510','observed');
INSERT INTO oc_entry VALUES(541,'Piece of Cake','https://boardgamegeek.com/thread/3512039','observed');
INSERT INTO oc_entry VALUES(542,'Rabbit Race','https://boardgamegeek.com/thread/3505789','observed');
INSERT INTO oc_entry VALUES(543,'Saltatorial','https://boardgamegeek.com/thread/3517033','observed');
INSERT INTO oc_entry VALUES(544,'Self Service','https://boardgamegeek.com/thread/3516181','observed');
INSERT INTO oc_entry VALUES(545,'Shadow Heist','https://boardgamegeek.com/thread/3513986','observed');
INSERT INTO oc_entry VALUES(546,'Ship Under Sabotage','https://boardgamegeek.com/thread/3488497','observed');
INSERT INTO oc_entry VALUES(547,'Sliminal Pursuit','https://boardgamegeek.com/thread/3513981','observed');
INSERT INTO oc_entry VALUES(548,'Some Strings Attached','https://boardgamegeek.com/thread/3512037','observed');
INSERT INTO oc_entry VALUES(549,'Way of the Goose','https://boardgamegeek.com/thread/3510065','observed');
INSERT INTO oc_entry VALUES(550,'Wobbly Bridge','https://boardgamegeek.com/thread/3503056','observed');
INSERT INTO oc_entry VALUES(551,'Zombie Apocalypse','https://boardgamegeek.com/thread/3514360','none_declared');
INSERT INTO oc_resource VALUES('514','https://drive.google.com/drive/folders/1T79Nx9oFPAMizHHwE1bYM5cU1AO8LCSn','game_files','folder','PDF files: V1.2','Cartella PDF versione 1.2.');
INSERT INTO oc_resource VALUES('515','https://docs.google.com/document/d/1M0kV2mZoObEAuRySrhesbO4_-8tvdWUkWLWanleHnPI/edit?usp=sharing','game_files','document','PnP Game & Rules','Gioco PnP e regole nello stesso documento.');
INSERT INTO oc_resource VALUES('516','https://drive.google.com/drive/folders/1ca8RvdogxImjQwrky-Ha93ExMwqk47gL?usp=drive_link','game_files','folder','Download the current Rules and Cards here','Regole e carta correnti.');
INSERT INTO oc_resource VALUES('517','https://www.youtube.com/watch?v=orujXqk_PG0','video','video','here','Video di gameplay.');
INSERT INTO oc_resource VALUES('517','https://drive.google.com/drive/folders/1hDMkEfZBeGyG8GIqj1CoGrOMlN6am6Yg?usp=drive_link','game_files','folder','here','File PnP.');
INSERT INTO oc_resource VALUES('518','https://piliapp.com/random/dice/?num=2','online_tool','web_app','Here','Dadi virtuali e annotazione degli elementi.');
INSERT INTO oc_resource VALUES('518','https://www.dropbox.com/scl/fi/i9lhhgjs8xs0z0t3h7eww/1C-Cuentame.pdf?rlkey=2iczuv091ycim0yx98pziq18w&st=27hy5m37&dl=0','component','file','Here/Aquí V.1.0','Carta versione 1.0.');
INSERT INTO oc_resource VALUES('518','https://www.dropbox.com/scl/fi/ske6o4x2mnhfgq668abkv/1C-Cuentame.V2.pdf?rlkey=5h6mzcxbt0h0sr2z99rzm8ix6&st=iiqf9qp4&dl=0','component','file','Here/Aquí V.2.0 New!','Carta versione 2.0.');
INSERT INTO oc_resource VALUES('518','https://www.dropbox.com/scl/fi/2639ivg5yssibl7cye0pv/Cuentame-R-Eng.pdf?rlkey=uiqay8qop565b33b8lsgyd4fe&st=uukbhc76&dl=0','rules','file','Here New!','Regole inglesi.');
INSERT INTO oc_resource VALUES('518','https://www.dropbox.com/scl/fi/lylzc5g6sx7y9cb8tv731/Cuentame-R-Esp.pdf?rlkey=j6t1k43721rsaujul3zzk4esu&st=e7zupzhn&dl=0','rules','file','Aquí ¡Nuevo!','Regole spagnole.');
INSERT INTO oc_resource VALUES('519','https://docs.google.com/document/d/e/2PACX-1vSYENqaXdFY6rTrmR2C5DCXVS8lDR-iKXJX5R1TGYh3MVEC8AzJ81h0vXxslewttCl_QCXnIntGxMeH/pub','rules','document','Rulebook','Regolamento pubblicato.');
INSERT INTO oc_resource VALUES('519','https://drive.google.com/file/d/1p6_amyTLmyGlst4xUKpZ0KtkjmOY9spn/view?usp=sharing','component','file','PnP Card','Carta PnP.');
INSERT INTO oc_resource VALUES('520','https://docs.google.com/document/d/1-mDsIbIs8pqr0fIK3tyAlqKT6Fb5lHBpG769izjCEIg/edit?usp=sharing','rules','document','Rules','Regolamento.');
INSERT INTO oc_resource VALUES('520','https://drive.google.com/file/d/1VmMt9kSVe7QDNDgOMqIgv9zir55srpXS/view?usp=share_link','component','file','PNP Truck Card','Carta camion PnP.');
INSERT INTO oc_resource VALUES('520','https://drive.google.com/file/d/1yF7ZnY3GuGfnw1IjdaDY4NT5XZUlyTyU/view?usp=share_link','component','file','Score Sheet','Foglio punteggio.');
INSERT INTO oc_resource VALUES('522','https://docs.google.com/document/d/14FtC-Dbi-HaKIJY9soE2COvX71u10-YhK78GBrvs_Xw/edit?usp=sharing','rules','document','Game Rules','Regole di gioco.');
INSERT INTO oc_resource VALUES('522','https://drive.google.com/file/d/17xGz8zyVjywGJJwxGtRdRGhX0DV_V_wg/view?usp=sharing','component','file','Game Card','Carta di gioco.');
INSERT INTO oc_resource VALUES('523','https://drive.google.com/open?id=1zcptfvhv41OlFuvqVzYIjSixTEsWE43p&usp=drive_fs','component','file','Operation D-2 - Print and Play','File PnP ancora etichettato col titolo storico Operation D-2.');
INSERT INTO oc_resource VALUES('523','https://docs.google.com/document/d/1cDvHG50SL38WdDQIWe0BU8CQ6rkeMK0-19P2ZgI0G9Y/edit?usp=sharing','rules','document','Finger Twister - Rulebook English','Regole inglesi.');
INSERT INTO oc_resource VALUES('523','https://docs.google.com/document/d/163DXgmMSj-N3U1OT2F8QjvFR-S6aKnfdWtv9DZHEk8Q/edit?usp=sharing','rules','document','Finger Twister - Reglamento Español','Regole spagnole.');
INSERT INTO oc_resource VALUES('524','https://drive.google.com/drive/folders/1bvVcv7bXpdr1QTW9GyVfnuWKQm6tPyon?usp=sharing','game_files','folder','https://drive.google.com/drive/folders/1bvVcv7bXpdr1QTW9GyVf...','Cartella condivisa dichiarata dall''autore.');
INSERT INTO oc_resource VALUES('525','https://docs.google.com/document/d/1QQJOl-lOGMWpDmWYyiuWakDvgIH0nKomaqkOcsbicBA/edit?tab=t.0','game_files','document','Download the current Rules and Cards here','Regole e carta correnti.');
INSERT INTO oc_resource VALUES('526','https://drive.google.com/drive/folders/1mlnzG6HcG2lektVTie9YzcX7OV3Tx_ui','game_files','folder','Honeybee and Dragonfly','Cartella Print and Play.');
INSERT INTO oc_resource VALUES('527','https://drive.google.com/file/d/1QigKqUiArest5rQ8ZRhNaEaMT8qF1WIw/view?usp=sharing','component','file','PnP Card','Carta PnP.');
INSERT INTO oc_resource VALUES('527','https://drive.google.com/file/d/1ztt1ob6LhT4jBfTC0qN8Uhw1n87_1p_M/view?usp=sharing','rules','file','Rules','Regolamento.');
INSERT INTO oc_resource VALUES('527','https://youtube.com/watch?v=LfagBSln8gY','video','video','How to Play - Hovercraft in a Minefield: Alligator Rescue','Video how-to-play; canale automatico escluso.');
INSERT INTO oc_resource VALUES('527','https://youtube.com/watch?v=rGCPK4YBi_M','video','video','Playthrough - Hovercraft in a Minefield: Alligator Rescue','Playthrough; canale automatico escluso.');
INSERT INTO oc_resource VALUES('528','https://www.dropbox.com/scl/fi/mt6qi2zdqff90kp40kla4/2-C-ITT.pdf?rlkey=d33n5osokp0uw1dvbd8p6vj27&st=jfpkzfhd&dl=0','component','file','Here / Aquí','Carta bilingue.');
INSERT INTO oc_resource VALUES('528','https://www.dropbox.com/scl/fi/98qldyt9ivirqyocexryd/1C-In-The-Trench.ENG.pdf?rlkey=0jpjqn68ohgl6kzroz0ae9cif&st=pwe39869&dl=0','rules','file','Here','Regole inglesi.');
INSERT INTO oc_resource VALUES('528','https://www.dropbox.com/scl/fi/eh10eig2ip9q5s12fqhzy/1C-In-The-Trench.ESP.pdf?rlkey=5v4zke2apqsix5rzsqn6jz61j&st=qq1w2odi&dl=0','rules','file','Aquí','Regole spagnole.');
INSERT INTO oc_resource VALUES('529','https://docs.google.com/document/d/1I3Qw1IiHsEEW-XILAo_zwZocxUGAt6rPUeF0xtDxJ8Y/edit?usp=sharing','rules','document','Rules - 1.1','Regole versione 1.1.');
INSERT INTO oc_resource VALUES('529','https://drive.google.com/file/d/1AnXMCLWejsEKQnEatE-Jypvfi-mpIitW/view?usp=sharing','component','file','Card - 1.0','Carta versione 1.0.');
INSERT INTO oc_resource VALUES('530','https://drive.google.com/drive/folders/1MQvgghobf6gMYH8kx-SgghkJCf_dBYkq?usp=drive_link','game_files','folder','Download the Rules and Print File here','Regole e file di stampa.');
INSERT INTO oc_resource VALUES('531','https://drive.google.com/file/d/1A2ljkOpSkUwpiHz9QEGJFPMdBUZdbVIk/view?usp=drive_link','game_files','file','Locky Dice v1.04 Rules and Card','Regole e carta versione 1.04.');
INSERT INTO oc_resource VALUES('531','https://drive.google.com/file/d/1pnsPqd_2KBrMjJ6-flz1CR9yp7DaJwMx/view?usp=drive_link','component','file','Locky Dice Card v1.04','Carta versione 1.04.');
INSERT INTO oc_resource VALUES('532','https://boardgamegeek.com/image/8819610','component','bgg_image','Tap the image above to print your copy','L''immagine BGG è dichiarata esplicitamente come copia da stampare.');
INSERT INTO oc_resource VALUES('533','https://drive.google.com/drive/folders/1fO10BPR8tmE-UgZRvosjCK1iCgC_Y4tQ?usp=sharing','game_files','folder','Matching Socks PNP Files (2025.05.31)','File correnti, PCIO e vecchia versione Shapelink.');
INSERT INTO oc_resource VALUES('533','https://playingcards.io/ju78uw','online_play','web_app','https://playingcards.io/ju78uw','Versione digitale.');
INSERT INTO oc_resource VALUES('535','https://drive.google.com/file/d/16eBGFb_rpqJHdv2N-cmdOL9SgaRhbjAj/view?usp=drive_link','game_files','file','DOWNLOAD LINK','Versione corrente Nap & Roll.');
INSERT INTO oc_resource VALUES('535','https://nap-and-roll-game.netlify.app/','online_play','web_app','NEW DIGITAL TEST','Test digitale.');
INSERT INTO oc_resource VALUES('535','https://drive.google.com/file/d/17l6XaitacmJSNp1IPVpfndgNfIc4oaR1/view?usp=sharing','game_files','file','VERSION 1 - Original Version','Versione originale (6)^3 preservata.');
INSERT INTO oc_resource VALUES('536','https://drive.google.com/drive/folders/15hP8l8gWGIwbvMv0rOOI8qy5wIbiuugU?usp=sharing','game_files','folder','PNP files Download link','File PnP.');
INSERT INTO oc_resource VALUES('537','https://drive.google.com/file/d/1tVC2xIOhCXxmTzIuyoW66MUNQDpJ7HC5/view','rules','file','Rulebook','Regolamento.');
INSERT INTO oc_resource VALUES('537','https://drive.google.com/file/d/1RBOvEQt8X5I7TZ1Nn8jCRa_8EJKKmIFj/view','component','file','PnP Card','Carta PnP.');
INSERT INTO oc_resource VALUES('537','https://greggjewell.io/onecardguard','online_tool','web_app','Dice Companion Web App','Companion per salute, focus e tiri.');
INSERT INTO oc_resource VALUES('537','https://www.youtube.com/watch?v=H8n7K3jABhI','audio','video','Here','Musica dichiarata per accompagnare la partita.');
INSERT INTO oc_resource VALUES('538','https://drive.google.com/file/d/1z6rHCGmafGSEb0sY73CAyWVUv5LhveTe/view','rules','file','One Intersection Rules v1.0','Regole versione 1.0.');
INSERT INTO oc_resource VALUES('538','https://drive.google.com/file/d/186SNUClS3iEuFdb7g0QSwcpnga4HO_9n/view','component','file','One Intersection Card v1.0','Carta versione 1.0.');
INSERT INTO oc_resource VALUES('538','https://drive.google.com/file/d/1W54NUBYRSARsIv5bvrJYeVjh_7qU1e9o/view','video','file','How to play video','Video how-to-play ospitato su Drive.');
INSERT INTO oc_resource VALUES('539','https://smallpdf.com/file#s=caaf96f9-31ae-49a2-abd5-e24c9651c185','rules','file','RULEBOOK (pdf)','Regolamento PDF.');
INSERT INTO oc_resource VALUES('539','https://steamcommunity.com/sharedfiles/filedetails/?id=3461399811','online_play','workshop_module','TabletopSimulator mod','Modulo Tabletop Simulator.');
INSERT INTO oc_resource VALUES('540','https://drive.google.com/drive/folders/1R-G9pMJe7NHasw9SYBqjlOaWFtodHriK?usp=sharing','game_files','folder','Print and play','Cartella Print and Play.');
INSERT INTO oc_resource VALUES('541','https://drive.google.com/drive/folders/1zpXykoay_xLG0y-3DZTlSWBqZyyne3yq?usp=sharing','game_files','folder','Print and Play','Cartella Print and Play.');
INSERT INTO oc_resource VALUES('542','https://drive.google.com/file/d/1mpNn8wa-79whfdH1IgU9zUAD0x30Z_OY/view?usp=drive_open','component','file','Rabbit Race - Card - Multilingual','Carta multilingue.');
INSERT INTO oc_resource VALUES('542','https://drive.google.com/file/d/1J3dDaxR1i-7-1mPhcUTz0HnJeTxUEt_V/view?usp=drive_open','rules','file','Rabbit Race - Rules - EN','Regole inglesi.');
INSERT INTO oc_resource VALUES('542','https://drive.google.com/file/d/1J4Xpx2gqjI6eggB0Dm30nXH7LTIOAMNJ/view?usp=drive_open','rules','file','Rabbit Race - Reglas - ES','Regole spagnole.');
INSERT INTO oc_resource VALUES('542','https://drive.google.com/file/d/1ydtSBvrfclQRYb23XZvKjvR195hzqb8d/view','video','file','Rabbit Race - Demo - EN','Demo inglese ospitata su Drive.');
INSERT INTO oc_resource VALUES('542','https://playingcards.io/5dabyx','online_play','web_app','PUBLIC ROOM','Stanza pubblica PlayingCards.io.');
INSERT INTO oc_resource VALUES('542','https://drive.google.com/file/d/1g851H-Vvhjuj2fzEEO4xlh9uXuQh58pg/view','online_play','file','File','File per stanza privata.');
INSERT INTO oc_resource VALUES('542','https://playingcards.io/import','online_tool','web_app','Import here','Pagina d''importazione esplicitamente indicata per la stanza privata.');
INSERT INTO oc_resource VALUES('543','https://drive.google.com/file/d/11R_ZkUk48-41DcTKgvjyWkzcdWQRt9ST/view?usp=sharing','component','file','1 Double-Sided Card','Carta fronte-retro.');
INSERT INTO oc_resource VALUES('543','https://docs.google.com/document/d/1g6c8UCbCEFEaS5beJsC2HcrAfyOBGAXLR5UwOULhpsU/edit?usp=sharing','rules','document','Printable doc version of this rulebook','Versione stampabile del regolamento.');
INSERT INTO oc_resource VALUES('544','https://drive.google.com/file/d/1HGkadu5_6AQqinLZQppfVrP4QgOUvOBr/view?usp=sharing','component','file','Self Service PnP File','File PnP.');
INSERT INTO oc_resource VALUES('544','https://drive.google.com/file/d/1EW8wJIvWVfoTJfyo7a6o-dSIR_GLXoyu/view?usp=sharing','rules','file','Self Service Rulebook','Regolamento.');
INSERT INTO oc_resource VALUES('545','https://drive.google.com/drive/folders/1bvVcv7bXpdr1QTW9GyVfnuWKQm6tPyon?usp=sharing','game_files','folder','https://drive.google.com/drive/folders/1bvVcv7bXpdr1QTW9GyVf...','Cartella condivisa dichiarata dall''autore.');
INSERT INTO oc_resource VALUES('546','https://docs.google.com/document/d/13AmFLBgsMWtPQLHeqbM_TkoOwYQaWUaQPDiTtcPkLkk/edit?usp=sharing','rules','document','Rules Beta','Regole beta.');
INSERT INTO oc_resource VALUES('546','https://drive.google.com/file/d/1I5s4dzbIDfyEqn6M3FCMs8ceYw1tZJyD/view?usp=sharing','component','file','S.U.S Card','Carta di gioco.');
INSERT INTO oc_resource VALUES('546','https://playingcards.io/ts7z3y','online_play','web_app','Playingcards.io','Versione PlayingCards.io.');
INSERT INTO oc_resource VALUES('547','https://drive.google.com/drive/folders/1bvVcv7bXpdr1QTW9GyVfnuWKQm6tPyon?usp=sharing','game_files','folder','https://drive.google.com/drive/folders/1bvVcv7bXpdr1QTW9GyVf...','Cartella condivisa dichiarata dall''autore.');
INSERT INTO oc_resource VALUES('548','https://c.gmx.net/@327464636691519389/CYMWDiaF2I8J_Eb4S3bXYA','game_files','file','Download rules and components here','Regole e componenti.');
INSERT INTO oc_resource VALUES('549','https://drive.google.com/file/d/1Iidg2RiCAb9-vn4sVyUEh9bmFt92aR03/view?usp=drive_link','game_files','file','Way of the Goose v1.02 Rules and Card Gutterfold','Regole e carta gutterfold versione 1.02.');
INSERT INTO oc_resource VALUES('550','https://drive.google.com/drive/folders/16fFitJ2BsGNSeVxvzalQLN9TavW96MfQ?usp=drive_link','game_files','folder','Wobbly Bridge Google drive','Cartella Google Drive.');
DELETE FROM entry_resource_scans WHERE checked_at='2026-09-11' AND entry_id IN (SELECT id FROM entries WHERE contest_id=15);
INSERT INTO entry_resource_scans(entry_id,checked_at,source_url,wip_status,resource_listing_status,notes) SELECT entry_id,'2026-09-11',wip_url,'found',listing_status,CASE listing_status WHEN 'observed' THEN 'Primo post renderizzato: anchor, link dinamici e media incorporati censiti; destinazioni non aperte.' WHEN 'none_declared' THEN 'Primo post renderizzato integralmente: nessun collegamento pertinente dichiarato osservato.' ELSE 'Post originale non osservabile; il primo articolo residuo appartiene a un altro utente e non è stato usato come fonte del gioco.' END FROM oc_entry;
INSERT OR IGNORE INTO remote_resources(game_id,kind,access_type,url,host,label,version_raw,availability_status,first_seen_at,last_verified_at) SELECT e.game_id,r.role,r.access_type,r.url,CASE WHEN instr(substr(r.url,instr(r.url,'//')+2),'/')>0 THEN substr(substr(r.url,instr(r.url,'//')+2),1,instr(substr(r.url,instr(r.url,'//')+2),'/')-1) ELSE substr(r.url,instr(r.url,'//')+2) END,r.label,NULL,'unknown','2026-09-11','2026-09-11' FROM oc_resource r JOIN entries e ON e.id=r.entry_id;
UPDATE remote_resources SET kind=(SELECT r.role FROM oc_resource r JOIN entries e ON e.id=r.entry_id WHERE e.game_id=remote_resources.game_id AND r.url=remote_resources.url),access_type=(SELECT r.access_type FROM oc_resource r JOIN entries e ON e.id=r.entry_id WHERE e.game_id=remote_resources.game_id AND r.url=remote_resources.url),label=(SELECT r.label FROM oc_resource r JOIN entries e ON e.id=r.entry_id WHERE e.game_id=remote_resources.game_id AND r.url=remote_resources.url),last_verified_at='2026-09-11' WHERE EXISTS(SELECT 1 FROM oc_resource r JOIN entries e ON e.id=r.entry_id WHERE e.game_id=remote_resources.game_id AND r.url=remote_resources.url);
DELETE FROM entry_resource_mentions WHERE entry_id IN (SELECT id FROM entries WHERE contest_id=15);
INSERT INTO entry_resource_mentions(entry_id,remote_resource_id,source_url,label_raw,content_role,is_primary,first_seen_at,last_seen_at) SELECT r.entry_id,rr.id,i.wip_url,r.label,r.role,CASE WHEN r.role='game_files' THEN 1 ELSE 0 END,'2026-09-11','2026-09-11' FROM oc_resource r JOIN oc_entry i ON i.entry_id=r.entry_id JOIN entries e ON e.id=r.entry_id JOIN remote_resources rr ON rr.game_id=e.game_id AND rr.url=r.url;
INSERT INTO remote_resource_observations(remote_resource_id,observed_at,evidence_url,observation_kind,availability_status,version_raw,notes) SELECT rr.id,'2026-09-11',i.wip_url,'declared_in_wip','not_checked',NULL,'Dichiarata nel primo post BGG; destinazione non aperta. Contesto: '||r.context||' Classificazione provvisoria.' FROM oc_resource r JOIN oc_entry i ON i.entry_id=r.entry_id JOIN entries e ON e.id=r.entry_id JOIN remote_resources rr ON rr.game_id=e.game_id AND rr.url=r.url WHERE NOT EXISTS(SELECT 1 FROM remote_resource_observations o WHERE o.remote_resource_id=rr.id AND o.observed_at='2026-09-11' AND o.evidence_url=i.wip_url AND o.observation_kind='declared_in_wip');
DROP TABLE oc_resource;
DROP TABLE oc_entry;
COMMIT;
