-- Declared gameplay materials from first posts only; rules were not opened or downloaded.
PRAGMA foreign_keys=ON;
BEGIN IMMEDIATE;
CREATE TEMP TABLE dm(entry_id,material_kind,name_normalized,name_raw,quantity_raw,requirement_level,supply_mode,context_raw);
INSERT INTO dm VALUES('793','randomizer','dado','dado','5 dadi','required','common','Components: 5 Dice');
INSERT INTO dm VALUES('793','writing_tool','matita','matita','1 per giocatore','required','common','Components: 1 Pencil p.p.');
INSERT INTO dm VALUES('793','printable_component','plancia civiltà','plancia civiltà','1 per giocatore','required','printable','Components: 1 Civ Board p.p.');
INSERT INTO dm VALUES('794','standard_deck','mazzo standard da 52 carte','mazzo standard da 52 carte','1','required','common','uses a standard 52 card deck');
INSERT INTO dm VALUES('794','writing_tool','penna o matita','penna o matita','1 per giocatore','required','common','a pen/pencil for each player');
INSERT INTO dm VALUES('794','printable_component','mappa e foglio di riferimento','mappa e foglio di riferimento','2–5 pagine','required','printable','Maps & Reference Sheet (2 - 5 pages)');
INSERT INTO dm VALUES('794','printable_component','pacchetto avventura','pacchetto avventura','4 pagine','alternative','printable','Adventure Pack 1: Kings (4 pages) OR Adventure Pack 2: Queens (4 pages)');
INSERT INTO dm VALUES('795','printable_component','foglio di gioco','foglio di gioco','1 foglio A4','required','printable','The printed game sheet (on a single sheet of printed A4 paper)');
INSERT INTO dm VALUES('795','randomizer','dado d6','dado d6','2','required','common','Two D6 dice');
INSERT INTO dm VALUES('795','writing_tool','penna o matita colorata','penna o matita colorata','1 per giocatore','required','common','A coloured pen/pencil per player');
INSERT INTO dm VALUES('796','printable_component','plancia','plancia','1 pagina','required','printable','1 Board (1 printed page) + 4D10 dice');
INSERT INTO dm VALUES('796','randomizer','dado d10','dado d10','4','required','common','1 Board (1 printed page) + 4D10 dice');
INSERT INTO dm VALUES('797','printable_component','foglio stampato','foglio stampato','2 per la prima partita','required','printable','Components Required: 2 printed sheets (for your first game... more required for the full game)');
INSERT INTO dm VALUES('797','randomizer','dado d6','dado d6','3','required','common','3 d6 dice');
INSERT INTO dm VALUES('797','writing_tool','strumento per scrivere','strumento per scrivere',NULL,'required','common','something to write with');
INSERT INTO dm VALUES('798','randomizer','dado d6','dado d6','1','required','common','1 d6 die');
INSERT INTO dm VALUES('798','randomizer','dado colorato','dado colorato','4','required','specialized','4 color dice (red, blue, yellow, green, purple, orange)');
INSERT INTO dm VALUES('798','writing_tool','matita colorata','matita colorata','6','required','common','6 colored pencils (red, blue, green, orange, purple, black)');
INSERT INTO dm VALUES('798','printable_component','foglio giocatore','foglio giocatore','1 per giocatore','required','printable','4 different playersheets');
INSERT INTO dm VALUES('798','writing_tool','matita','matita','1 per giocatore','required','common','1 pencil per player');
INSERT INTO dm VALUES('799','printable_component','foglio stampato fronte-retro','foglio stampato fronte-retro','2','required','printable','Components: 2 Printed sheets (double-sided)');
INSERT INTO dm VALUES('799','randomizer','dado d6','dado d6','3','required','common','3 six-sided dice');
INSERT INTO dm VALUES('799','writing_tool','penna o matita','penna o matita',NULL,'required','common','pen or pencil');
INSERT INTO dm VALUES('801','randomizer','dado','dado','3','required','common','3 dice');
INSERT INTO dm VALUES('801','printable_component','foglio di gioco','foglio di gioco','1','required','printable','1 sheet');
INSERT INTO dm VALUES('802','printable_component','carta opportunità','carta opportunità','32','required','printable','Opportunity cards (32 pcs)');
INSERT INTO dm VALUES('802','printable_component','carta token','carta token','14 per giocatore','required','printable','token cards (14/player)');
INSERT INTO dm VALUES('802','printable_component','foglio punteggio','foglio punteggio','1 per giocatore','required','printable','score sheets (aka Thief Sheet) (1/player)');
INSERT INTO dm VALUES('802','randomizer','set di dadi poliedrici','set di dadi poliedrici','2 d4, 2 d6, 2 d8, 1 d10','required','specialized','dices (2 d4, 2 d6, 2 d8 and 1 d10)');
INSERT INTO dm VALUES('803','printable_component','foglio giocatore','foglio giocatore',NULL,'required','printable','Player sheet');
INSERT INTO dm VALUES('803','printable_component','carta obiettivo','carta obiettivo',NULL,'required','printable','Goal cards');
INSERT INTO dm VALUES('803','randomizer','dado','dado',NULL,'required','common','Dice will be used to create terrain and to populate it with animals.');
INSERT INTO dm VALUES('804','randomizer','dado','dado',NULL,'required','common','All you need to play this game is dice and a pen!');
INSERT INTO dm VALUES('804','writing_tool','penna','penna','1','required','common','All you need to play this game is dice and a pen!');
INSERT INTO dm VALUES('805','randomizer','dado d6','dado d6','4','required','common','Components needed are 4 D6');
INSERT INTO dm VALUES('805','printable_component','foglio giocatore','foglio giocatore','1 per giocatore','required','printable','a player sheet ... for each player');
INSERT INTO dm VALUES('805','writing_tool','penna o matita','penna o matita','1 per giocatore','required','common','a pen/pencil for each player');
INSERT INTO dm VALUES('807','printable_component','foglio giocatore','foglio giocatore',NULL,'required','printable','Components - Player sheets 2.0');
INSERT INTO dm VALUES('807','printable_component','carta parola','carta parola','54','required','printable','54 word cards');
INSERT INTO dm VALUES('807','writing_tool','matita','matita','1','required','common','Pencil (quill & ink)');
INSERT INTO dm VALUES('809','printable_component','plancia di gioco','plancia di gioco','1','required','printable','Components: Gameboard');
INSERT INTO dm VALUES('809','randomizer','dado bianco','dado bianco','5','required','common','5 white dice');
INSERT INTO dm VALUES('809','randomizer','dado di colore diverso','dado di colore diverso','1','required','common','1 die of another color');
INSERT INTO dm VALUES('810','printable_component','carte di gioco','carte di gioco','oltre 100','required','printable','print and cut out over 100 cards');
INSERT INTO dm VALUES('810','printable_component','foglio protagonista','foglio protagonista','1 per giocatore','required','printable','Each player has a Protagonist sheet');
INSERT INTO dm VALUES('810','printable_component','carta scapolo','carta scapolo','3 per giocatore','required','printable','3 Bachelor cards they can write on');
INSERT INTO dm VALUES('810','printable_component','mazzo iniziale','mazzo iniziale','11 carte per giocatore','required','printable','an 11 card starter deck');
INSERT INTO dm VALUES('810','printable_component','carte obiettivo e incontro','carte obiettivo e incontro',NULL,'required','printable','Link to Objective and Encounter Cards');
INSERT INTO dm VALUES('811','standard_deck','mazzo standard da 52 carte','mazzo standard da 52 carte','1','required','common','Additional Components: Standard 52 Deck');
INSERT INTO dm VALUES('811','writing_tool','matita o pennarello cancellabile','matita o pennarello cancellabile','1 per giocatore','required','common','Pencil or Dry Erase Marker for each player');
INSERT INTO dm VALUES('813','randomizer','dado d6','dado d6','7','required','common','Components: 7 d6');
INSERT INTO dm VALUES('813','token_marker','segnalino trasparente','segnalino trasparente','7 per giocatore','required','specialized','7 markers (better if they are transparent) per player');
INSERT INTO dm VALUES('813','printable_component','foglio giocatore','foglio giocatore','1 per giocatore','required','printable','One sheet per player');
INSERT INTO dm VALUES('814','printable_component','foglio di marcatura','foglio di marcatura','2','required','printable','2 Marking Sheets');
INSERT INTO dm VALUES('814','randomizer','dado d6 comune','dado d6 comune','4','required','common','4 Common Dice (D6): Any Color can be used');
INSERT INTO dm VALUES('814','randomizer','dado d6 di colore diverso','dado d6 di colore diverso','1','required','common','1 Common Dice (D6): Different color');
INSERT INTO dm VALUES('814','printable_component','carta','carta','24','required','printable','24 Cards (10 Blue Cards, 6 Red Cards and 8 Gray Cards)');
INSERT INTO dm VALUES('814','token_marker','segnalino','segnalino','4','required','supplied_or_printable','4 Markers: (2 Researchers and 2 Rats)');
INSERT INTO dm VALUES('815','printable_component','pagina giocatore','pagina giocatore','1 per giocatore','required','printable','1 page per player');
INSERT INTO dm VALUES('815','printable_component','pagina drago','pagina drago','1','required','printable','1 page for the dragon');
INSERT INTO dm VALUES('815','randomizer','dado d6','dado d6','2','required','common','Bring your own items: 2 D6 dice');
INSERT INTO dm VALUES('815','token_marker','pedina giocatore','pedina giocatore','2','required','common','2 player-tokens');
INSERT INTO dm VALUES('816','printable_component','foglio di gioco','foglio di gioco','1','required','printable','City Lights is ... played on a single sheet');
INSERT INTO dm VALUES('816','randomizer','dado d6','dado d6','3','required','common','3 six-sided dice');
INSERT INTO dm VALUES('816','writing_tool','pennarello nero','pennarello nero','1','required','common','1 black marker');
INSERT INTO dm VALUES('816','writing_tool','pennarello colore caldo','pennarello colore caldo','1','required','common','1 warm colored marker (usually yellow)');
INSERT INTO dm VALUES('816','writing_tool','pennarello colore freddo','pennarello colore freddo','1','required','common','1 cool colored marker (usually blue)');
INSERT INTO dm VALUES('817','printable_component','plancia round','plancia round','1','required','printable','1 round board');
INSERT INTO dm VALUES('817','printable_component','carte gioco base','carte gioco base','36','required','printable','36 cards for the base game');
INSERT INTO dm VALUES('817','printable_component','carte espansione','carte espansione','7','optional','printable','7 cards for the add-on');
INSERT INTO dm VALUES('817','printable_component','foglio giocatore','foglio giocatore',NULL,'required','printable','player sheets');
INSERT INTO dm VALUES('817','writing_tool','penna','penna','1','required','common','Needed: pen');
INSERT INTO dm VALUES('817','randomizer','dado d6','dado d6','5','required','common','5 6-sided dice (4 regular, 1 special)');
INSERT INTO dm VALUES('818','printable_component','foglio stampato','foglio stampato','2','required','printable','Components: 2 Printed Sheets');
INSERT INTO dm VALUES('818','writing_tool','penna','penna','1','required','common','Components: ... Pen');
INSERT INTO dm VALUES('818','randomizer','dado d6','dado d6','2','required','common','Components: ... 2x D6');
INSERT INTO dm VALUES('818','digital_device','telefono cellulare','telefono cellulare','1','required','digital_device','Components: ... Mobile Phone');
INSERT INTO dm VALUES('821','randomizer','dado d6','dado d6','6 per giocatore','required','common','Each player will need: 6 6-sided dice');
INSERT INTO dm VALUES('821','printable_component','materiali papercraft o stampa 3D','materiali papercraft o stampa 3D',NULL,'required','supplied_or_printable','Papercraft or 3D printed materials');
INSERT INTO dm VALUES('822','printable_component','foglio principale e foglio pianeta','foglio principale e foglio pianeta','2','required','printable','print the Main Game Sheet, a Planet Sheet');
INSERT INTO dm VALUES('822','writing_tool','matita','matita','1','required','common','a pencil');
INSERT INTO dm VALUES('822','randomizer','dado d6','dado d6','1','required','common','a D6');
INSERT INTO dm VALUES('823','printable_component','foglio di gioco','foglio di gioco','1','required','printable','Components: 1x Play sheet');
INSERT INTO dm VALUES('823','randomizer','dado bianco','dado bianco','2','required','common','2x White Dice');
INSERT INTO dm VALUES('823','randomizer','dado nero','dado nero','2','required','common','2x Black Dice');
INSERT INTO dm VALUES('823','randomizer','dado colorato','dado colorato','4 (rosso, verde, giallo, blu)','required','common','1x Red, Green, Yellow and Blue Dice');
INSERT INTO dm VALUES('823','timer','timer','timer','1','required','household','1x Timer (you can use your phone)');
INSERT INTO dm VALUES('824','writing_tool','matita','matita','1','required','common','Additional Components: Pencil');
INSERT INTO dm VALUES('824','randomizer','dado','dado','4, preferibilmente uno diverso','required','common','4 Dice (preferably 1 of a different colour)');
INSERT INTO dm VALUES('828','printable_component','plancia 18×18','plancia 18×18','1','required','printable','The 18x18 gameboard');
INSERT INTO dm VALUES('366','printable_component','carta fronte-retro','carta fronte-retro',NULL,'required','printable','cards are set up for duplex print');
INSERT INTO dm VALUES('367','printable_component','carta incontro','carta incontro','14','required','printable','Components: 14 Encounter Cards');
INSERT INTO dm VALUES('367','printable_component','carta cancello','carta cancello','1','required','printable','1 Gate Card');
INSERT INTO dm VALUES('367','printable_component','carta negozio','carta negozio','1','required','printable','1 Shop Card');
INSERT INTO dm VALUES('367','printable_component','carta personaggio','carta personaggio','1','required','printable','1 Character Card');
INSERT INTO dm VALUES('367','printable_component','carta salute','carta salute','1','required','printable','1 Health card');
INSERT INTO dm VALUES('368','printable_component','carta','carta','16','required','printable','One Banner is a fully deterministic 16-card game');
INSERT INTO dm VALUES('369','printable_component','carta','carta','18','required','printable','18 cards: 13 Magpies, 4 Trees, 1 Spectre of Sorrows');
INSERT INTO dm VALUES('370','printable_component','carta','carta','18 + 2 boss','required','printable','18 cards (plus 2 additional Boss cards)');
INSERT INTO dm VALUES('371','printable_component','carta labirinto','carta labirinto','2 per puzzle','required','printable','Each puzzle is made up of two cards');
INSERT INTO dm VALUES('372','printable_component','carta fronte-retro','carta fronte-retro',NULL,'required','printable','all cards with bleed + left handed versions');
INSERT INTO dm VALUES('373','printable_component','carta fronte-retro','carta fronte-retro','27','required','printable','Components: 27 double-sided Cards');
INSERT INTO dm VALUES('373','household_item','clip fermacarte mini','clip fermacarte mini','1','required','household','mini-sized binder clip');
INSERT INTO dm VALUES('373','household_item','graffetta','graffetta','5','required','household','5 paper clips');
INSERT INTO dm VALUES('375','printable_component','carta','carta','27','required','printable','Components: 27 cards');
INSERT INTO dm VALUES('377','printable_component','carta missione','carta missione','14','required','printable','Components: 14 Mission cards');
INSERT INTO dm VALUES('377','printable_component','carte tracciamento','carte tracciamento','4','required','printable','1 Favor card, 1 Tracker card, 1 Credit card, 1 Inventory card');
INSERT INTO dm VALUES('378','printable_component','carta','carta','18','required','printable','Withering Grove is an 18-card game');
INSERT INTO dm VALUES('380','printable_component','carte fronte-retro','carte fronte-retro','45','required','printable','1 Round Tracker, 1 Cat, 6 Hazard Cards, 37 Stacks Cards');
INSERT INTO dm VALUES('380','accessory','portacarte personalizzato a tre tasche','portacarte personalizzato a tre tasche','1','required','printable','1 Library Cart [custom 3-pocket card holder]');
INSERT INTO dm VALUES('380','household_item','graffetta','graffetta','1','required','household','1 Paperclip ... used to track Rounds');
INSERT INTO dm VALUES('380','assembly_material','cartoncino o cartone 8×11','cartoncino o cartone 8×11','2 fogli','required','household','requires 2 blank 8×11 sheets of cardstock or cardboard');
INSERT INTO dm VALUES('380','assembly_tool','nastro trasparente','nastro trasparente',NULL,'required','household','Clear tape, scissors, and a ruler are also required for initial assembly');
INSERT INTO dm VALUES('380','assembly_tool','forbici','forbici',NULL,'required','household','Clear tape, scissors, and a ruler are also required for initial assembly');
INSERT INTO dm VALUES('380','assembly_tool','righello','righello',NULL,'required','household','Clear tape, scissors, and a ruler are also required for initial assembly');
INSERT INTO dm VALUES('382','printable_component','carta fronte-retro','carta fronte-retro','18','required','printable','Components: 18 Cards - Front and back');
INSERT INTO dm VALUES('383','printable_component','carta edificio fronte-retro','carta edificio fronte-retro','18','required','printable','Components: 18 Double-sided Building Cards');
INSERT INTO dm VALUES('385','printable_component','mazzo di carte','mazzo di carte','29 da un pool di 45','required','printable','played using a deck of 29 cards (from an available pre-game pool of 45)');
INSERT INTO dm VALUES('387','printable_component','carta','carta','9 per giocatore','required','printable','Each player has 9 cards in their hand');
INSERT INTO dm VALUES('389','printable_component','carta quadrata','carta quadrata','30','required','printable','Components: 30 cards');
INSERT INTO dm VALUES('390','printable_component','carta percorso','carta percorso','7','required','printable','Components: 7 Trail cards');
INSERT INTO dm VALUES('390','printable_component','carta checkpoint','carta checkpoint','1','required','printable','1 Checkpoint card');
INSERT INTO dm VALUES('392','printable_component','carta','carta','18','required','printable','Components: 18 Cards');
INSERT INTO dm VALUES('487','printable_component','carta','carta',NULL,'required','printable','Components, including: Cards');
INSERT INTO dm VALUES('487','printable_component','tessera punteggio','tessera punteggio',NULL,'required','printable','Scoring Tiles');
INSERT INTO dm VALUES('488','printable_component','tessera vita marina','tessera vita marina',NULL,'required','printable','Players will take turn flipping over two tiles');
INSERT INTO dm VALUES('488','printable_component','carta tesoro','carta tesoro','12','required','printable','If both players find all 12 treasures');
INSERT INTO dm VALUES('488','token_marker','gettone tempo','gettone tempo',NULL,'required','supplied_or_printable','take a time token');
INSERT INTO dm VALUES('489','printable_component','carta','carta','64','required','printable','Components: 64 cards');
INSERT INTO dm VALUES('490','randomizer','dado personalizzato','dado personalizzato','3','required','supplied_or_printable','rolling 3 dice with Colors and Swirl Patterns');
INSERT INTO dm VALUES('490','printable_component','tessera spirale','tessera spirale','42 fronte-retro','required','printable','42 double sided swirly tiles');
INSERT INTO dm VALUES('491','printable_component','materiali PnP','materiali PnP',NULL,'required','printable','No components needed beyond the pnp files');
INSERT INTO dm VALUES('491','printable_component','plancia giocatore','plancia giocatore',NULL,'optional','printable','Optional player boards are also printable');
INSERT INTO dm VALUES('494','printable_component','carte gioco','carte gioco',NULL,'required','printable','Components and Rules');
INSERT INTO dm VALUES('494','standard_deck','mazzo tradizionale','mazzo tradizionale',NULL,'alternative','common','A traditional deck will work for 2 players');
INSERT INTO dm VALUES('495','randomizer','dado','dado',NULL,'required','common','Roll and assign dice');
INSERT INTO dm VALUES('495','printable_component','plancia esagonale','plancia esagonale','1','required','printable','hexagonal game board');
INSERT INTO dm VALUES('495','token_marker','pedina ape','pedina ape',NULL,'required','supplied_or_printable','managing bees on a hexagonal game board');
INSERT INTO dm VALUES('496','token_marker','pedina coniglio','pedina coniglio','12','required','supplied_or_printable','12x Bunny player pieces');
INSERT INTO dm VALUES('496','printable_component','carte','carte','98','required','printable','6 Character, 60 Move, 30 Momentum, 2 Momma/Bedtime Story cards');
INSERT INTO dm VALUES('496','token_marker','pedina oggetto','pedina oggetto','3','required','supplied_or_printable','3x Item pieces');
INSERT INTO dm VALUES('496','printable_component','plancia tracciaturno','plancia tracciaturno','1','required','printable','1x Turn Tracker Board');
INSERT INTO dm VALUES('496','printable_component','plancia pista fronte-retro','plancia pista fronte-retro','3','required','printable','3x two-sided Racetrack Boards');
INSERT INTO dm VALUES('497','printable_component','piattaforma finale','piattaforma finale','1','required','printable','Basic Components: Finishing platform');
INSERT INTO dm VALUES('497','printable_component','supporto bonus','supporto bonus','6','required','printable','6 Bonus Stands');
INSERT INTO dm VALUES('497','token_marker','gettone salute','gettone salute','30','required','supplied_or_printable','30 Health tokens');
INSERT INTO dm VALUES('497','printable_component','carta Chi','carta Chi',NULL,'required','printable','Chi-Cards');
INSERT INTO dm VALUES('497','crafted_component','rana origami','rana origami',NULL,'required','household','Craft a paper jumping frog');
INSERT INTO dm VALUES('498','printable_component','plancia e carte','plancia e carte',NULL,'required','printable','components required: the printed board and cards');
INSERT INTO dm VALUES('498','randomizer','dado colorato','dado colorato','4 per giocatore','required','common','4 dice per player, preferably blue, red, yellow and green');
INSERT INTO dm VALUES('500','printable_component','carta espressione','carta espressione','64','required','printable','Components: 64 expression cards');
INSERT INTO dm VALUES('501','printable_component','carta gioco base','carta gioco base','108','required','printable','88 Regular Cards and 20 Special Cards');
INSERT INTO dm VALUES('501','token_marker','noce / gettone ghianda','noce / gettone ghianda','50','required','supplied_or_printable','50 Nuts (Acorn Tokens)');
INSERT INTO dm VALUES('501','household_item','monete, caramelle o fiches','monete, caramelle o fiches','50','alternative','household','Use 50 coins, mints, candies, bingo chips ... in place of the Nuts');
INSERT INTO dm VALUES('502','printable_component','carta nuvola','carta nuvola','50','required','printable','Components needed: 50 cloud cards');
INSERT INTO dm VALUES('502','printable_component','carta numero','carta numero','5','required','printable','5 number cards');
INSERT INTO dm VALUES('502','token_marker','gettone punto','gettone punto',NULL,'required','supplied_or_printable','tokens for points');
INSERT INTO dm VALUES('503','printable_component','carta','carta','28','required','printable','The game uses 28 cards');
INSERT INTO dm VALUES('503','randomizer','dado','dado','fino a 5','required','common','place up to 5 dice onto the available schools');
INSERT INTO dm VALUES('504','printable_component','tessera isola','tessera isola',NULL,'required','printable','Components: Island Tiles');
INSERT INTO dm VALUES('504','token_marker','pedina giocatore / meeple','pedina giocatore / meeple','6','required','common','6 Player Tokens ... I use meeples');
INSERT INTO dm VALUES('504','household_item','pasta adesiva blu','pasta adesiva blu',NULL,'optional','household','meeples with blue tac ... to help turn over cards');
INSERT INTO dm VALUES('504','printable_component','carta vita','carta vita','18','required','printable','18 Life Cards');
INSERT INTO dm VALUES('504','printable_component','carta risorsa','carta risorsa','27','required','printable','7 Berries, 6 Knives, 6 Ropes, 8 Water Canteens');
INSERT INTO dm VALUES('505','printable_component','plancia','plancia','1','required','printable','Components: 1 Board');
INSERT INTO dm VALUES('505','printable_component','carta pesce','carta pesce','21','required','printable','21 Fish Cards');
INSERT INTO dm VALUES('505','token_marker','gettone pesce','gettone pesce','30','required','supplied_or_printable','30 Fish Tokens');
INSERT INTO dm VALUES('505','token_marker','pedina sirena','pedina sirena','4','required','supplied_or_printable','4 Mermaid Tokens');
INSERT INTO dm VALUES('505','token_marker','pedina dinosauro','pedina dinosauro','1','required','supplied_or_printable','1 Dinosaur Token');
INSERT INTO dm VALUES('505','printable_component','carta primo giocatore','carta primo giocatore','1','required','printable','1 First Player card');
INSERT INTO dm VALUES('506','writing_tool','segnalino o penna','segnalino o penna','1','required','common','An additional marker or pen is required to play');
INSERT INTO dm VALUES('507','printable_component','plancia esagonale','plancia esagonale','1 (37 esagoni)','required','printable','37 hex grid board');
INSERT INTO dm VALUES('507','token_marker','pedina','pedina','6 in 2 colori','required','common','6 pawns in 2 different colors');
INSERT INTO dm VALUES('507','token_marker','tessera ghiaccio / pietra','tessera ghiaccio / pietra','37','alternative','common','37 ice tiles ... use checkers, meeples, etc');
INSERT INTO dm VALUES('508','printable_component','carta','carta','62','required','printable','Components: 62 cards');
INSERT INTO dm VALUES('508','printable_component','tessera bonus passaggio','tessera bonus passaggio','6','required','printable','6 passing bonus tiles');
INSERT INTO dm VALUES('508','token_marker','miniatura cioccolato','miniatura cioccolato','13','required','specialized','13 chocolate minis');
INSERT INTO dm VALUES('508','printable_component','tracciato limite collettivo','tracciato limite collettivo','1','required','printable','1 collective limit track');
INSERT INTO dm VALUES('508','token_marker','segnalino limite collettivo','segnalino limite collettivo','1','required','common','1 collective limit marker');
INSERT INTO dm VALUES('508','household_item','cubetto o disco di legno','cubetto o disco di legno',NULL,'alternative','household','wooden cubes or discs will work fine');
INSERT INTO dm VALUES('509','printable_component','plancia','plancia','1','required','printable','Components: 1 board');
INSERT INTO dm VALUES('509','token_marker','gettone foglia','gettone foglia','15','required','supplied_or_printable','15 leaf tokens');
INSERT INTO dm VALUES('509','token_marker','pedina giocatore','pedina giocatore','2–4','required','supplied_or_printable','2–4 player tokens');
INSERT INTO dm VALUES('509','randomizer','dado d6','dado d6','1','required','common','1 regular die (D6)');
INSERT INTO dm VALUES('510','randomizer','dado d6','dado d6','molti, preferibilmente 3 colori','required','common','requires 6 sided dice ... preferably lots of dice ... three different colors');
INSERT INTO dm VALUES('510','scoring_tool','plancia cribbage','plancia cribbage','1','optional','household','A cribbage board can be useful to keep score');
INSERT INTO dm VALUES('510','household_item','foglio di carta','foglio di carta','1','alternative','household','or just use a piece of paper');
INSERT INTO dm VALUES('510','token_marker','gettone colorato o fiche poker','gettone colorato o fiche poker',NULL,'required','household','Colored tokens or different color poker chips ... track bets');
INSERT INTO dm VALUES('511','printable_component','carta prompt','carta prompt','20','required','printable','20 prompt cards');
INSERT INTO dm VALUES('511','printable_component','foglio da disegno','foglio da disegno','1 per giocatore','required','printable','Drawing sheets (1 per player)');
INSERT INTO dm VALUES('511','writing_tool','matita o penna','matita o penna','1 per giocatore','required','common','Pencil or Pen (1 per player)');
INSERT INTO dm VALUES('511','token_marker','gettone punto','gettone punto','3','required','supplied_or_printable','3 Point Tokens');
INSERT INTO dm VALUES('511','randomizer','dado d6','dado d6','1','required','common','6-sided dice');
INSERT INTO dm VALUES('511','printable_component','foglio punteggio','foglio punteggio','1','required','printable','Score sheet');
INSERT INTO dm VALUES('513','printable_component','plancia parco','plancia parco','4','required','printable','4 amusement park player boards');
INSERT INTO dm VALUES('513','printable_component','plancia round','plancia round','1','required','printable','1 round board');
INSERT INTO dm VALUES('513','printable_component','carte','carte','115','required','printable','90 attraction, 10 action, 15 planning cards');
INSERT INTO dm VALUES('513','token_marker','meeple visitatore','meeple visitatore','100','required','specialized','100 visitor meeples');
INSERT INTO dm VALUES('513','token_marker','segnalino giocatore','segnalino giocatore','4','required','common','4 player markers');
INSERT INTO dm VALUES('513','token_marker','segnalino round','segnalino round','1','required','common','1 round marker');
INSERT INTO dm VALUES('513','token_marker','segnalino primo giocatore','segnalino primo giocatore','1','required','common','1 first player marker');
DELETE FROM entry_material_requirements WHERE entry_id IN (SELECT id FROM entries WHERE contest_id IN (12,14,22));
INSERT INTO entry_material_requirements(entry_id,material_kind,name_normalized,name_raw,quantity_raw,requirement_level,supply_mode,context_raw,source_url,first_seen_at,last_seen_at) SELECT d.entry_id,d.material_kind,d.name_normalized,d.name_raw,d.quantity_raw,d.requirement_level,d.supply_mode,d.context_raw,e.wip_thread_url,'2026-09-11','2026-09-11' FROM dm d JOIN entries e ON e.id=d.entry_id;
DELETE FROM entry_material_scans WHERE checked_at='2026-09-11' AND coverage_scope='first_post_only' AND entry_id IN (SELECT id FROM entries WHERE contest_id IN (12,14,22));
INSERT INTO entry_material_scans(entry_id,checked_at,source_url,wip_status,material_listing_status,coverage_scope,notes) SELECT e.id,'2026-09-11',COALESCE(e.wip_thread_url,e.entry_url),CASE WHEN e.wip_thread_url IS NULL THEN 'not_found' ELSE 'found' END,CASE WHEN e.id=391 THEN 'not_observable' WHEN e.wip_thread_url IS NULL THEN 'not_checked' WHEN EXISTS(SELECT 1 FROM dm WHERE dm.entry_id=e.id) THEN 'observed' ELSE 'none_declared' END,'first_post_only',CASE WHEN e.id=391 THEN 'Post originale non osservabile; nessun requisito inventato.' WHEN e.wip_thread_url IS NULL THEN 'WIP non individuato; la voce di roster non sostituisce il primo post.' WHEN EXISTS(SELECT 1 FROM dm WHERE dm.entry_id=e.id) THEN 'Materiali di gioco esplicitamente dichiarati nel primo post; le regole non sono state aperte né scaricate.' ELSE 'Nessun requisito materiale sufficientemente esplicito osservato nel primo post; le regole potranno integrare il censimento.' END FROM entries e WHERE e.contest_id IN (12,14,22);
DROP TABLE dm;
COMMIT;
