-- Full first-post resource census for 2025 In-Hand. External destinations were not opened.
PRAGMA foreign_keys = ON;
BEGIN IMMEDIATE;
CREATE TEMP TABLE ih_entry(entry_id INTEGER PRIMARY KEY,title TEXT NOT NULL,wip_url TEXT,listing_status TEXT NOT NULL);
CREATE TEMP TABLE ih_resource(entry_id INTEGER,url TEXT,role TEXT,access_type TEXT,label TEXT,context TEXT,PRIMARY KEY(entry_id,url));
INSERT INTO ih_entry VALUES(366,'Crop Rotation','https://boardgamegeek.com/thread/3378438','observed');
INSERT INTO ih_entry VALUES(367,'Hand of Cthulhu','https://boardgamegeek.com/thread/3379033','observed');
INSERT INTO ih_entry VALUES(368,'One Banner','https://boardgamegeek.com/thread/3379074','observed');
INSERT INTO ih_entry VALUES(369,'One for sorrow','https://boardgamegeek.com/thread/3388854','observed');
INSERT INTO ih_entry VALUES(370,'Valley of Gems','https://boardgamegeek.com/thread/3399221','observed');
INSERT INTO ih_entry VALUES(371,'Maze Shift','https://boardgamegeek.com/thread/3384043','observed');
INSERT INTO ih_entry VALUES(372,'Hand-At-Arms','https://boardgamegeek.com/thread/3402467','observed');
INSERT INTO ih_entry VALUES(373,'Office Quest: Data Kraken','https://boardgamegeek.com/thread/3402030','observed');
INSERT INTO ih_entry VALUES(374,'Dive Into The Dungeon','https://boardgamegeek.com/thread/3408691','observed');
INSERT INTO ih_entry VALUES(375,'Publish or Perish','https://boardgamegeek.com/thread/3413650','observed');
INSERT INTO ih_entry VALUES(376,'Songs of the Sea and the Sky','https://boardgamegeek.com/thread/3419526','observed');
INSERT INTO ih_entry VALUES(377,'Smuggler''s Sky: Hand of Fate','https://boardgamegeek.com/thread/3425444','observed');
INSERT INTO ih_entry VALUES(378,'Withering Grove','https://boardgamegeek.com/thread/3425504','observed');
INSERT INTO ih_entry VALUES(379,'Spellbooked!','https://boardgamegeek.com/thread/3430680','observed');
INSERT INTO ih_entry VALUES(380,'Librarian’s Cat','https://boardgamegeek.com/thread/3431954','observed');
INSERT INTO ih_entry VALUES(381,'Duel: Clash of Metal',NULL,'not_checked');
INSERT INTO ih_entry VALUES(382,'Handicam','https://boardgamegeek.com/thread/3423424','observed');
INSERT INTO ih_entry VALUES(383,'Downtown Las Palmas','https://boardgamegeek.com/thread/3410393','observed');
INSERT INTO ih_entry VALUES(384,'Hellheim In-Hand Duel','https://boardgamegeek.com/thread/3403303','none_declared');
INSERT INTO ih_entry VALUES(385,'Prime Minister - The In-Hand Game','https://boardgamegeek.com/thread/3378860','observed');
INSERT INTO ih_entry VALUES(386,'Starcrossed','https://boardgamegeek.com/thread/3400721','observed');
INSERT INTO ih_entry VALUES(387,'HandMaze','https://boardgamegeek.com/thread/3423398','observed');
INSERT INTO ih_entry VALUES(388,'Dreadspire Keep','https://boardgamegeek.com/thread/3429956','none_declared');
INSERT INTO ih_entry VALUES(389,'Awake until midnight','https://boardgamegeek.com/thread/3425454','observed');
INSERT INTO ih_entry VALUES(390,'On the Trail of the Letter Cutter','https://boardgamegeek.com/thread/3388256','observed');
INSERT INTO ih_entry VALUES(391,'Black Market','https://boardgamegeek.com/thread/3431335','not_observable');
INSERT INTO ih_entry VALUES(392,'Memory Trick','https://boardgamegeek.com/thread/3388612','observed');
INSERT INTO ih_resource VALUES('366','https://boardgamegeek.com/boardgame/446250/crop-rotation/files','game_files','download_page','here in the game page''s files section','Files now hosted in the BGG game-page files section.');
INSERT INTO ih_resource VALUES('366','https://playingcards.io/cw9xhm','online_play','web_app','online on pc.io here','Alternative online play without printing cards.');
INSERT INTO ih_resource VALUES('367','https://youtube.com/watch?v=jNZQVbfbphg','video','video','How to Play Hand of Cthulhu','Embedded how-to-play video; automatic channel link excluded.');
INSERT INTO ih_resource VALUES('367','https://playingcards.io/zp6weh','online_play','web_app','If you want to play online click here for PlayingCards.io!','PlayingCards.io online version.');
INSERT INTO ih_resource VALUES('367','https://onecardmaze.myshopify.com/','project_page','download_page','If you want to buy the PnP or the Physical Wallet click here!','Page offering the PnP or a physical wallet edition.');
INSERT INTO ih_resource VALUES('368','https://qu1rrel.itch.io/one-banner','game_files','download_page','Game Files','Game files page.');
INSERT INTO ih_resource VALUES('368','https://playingcards.io/game/standard-deck','online_play','web_app','PlayingCards.io','PlayingCards.io version declared under ''To try the game''.');
INSERT INTO ih_resource VALUES('368','https://youtube.com/watch?v=k-dOAnbAvRY','video','video','OneBanner Playthrough 241208','Embedded playthrough videos; duplicate automatic channel links excluded.');
INSERT INTO ih_resource VALUES('368','https://youtube.com/watch?v=m2ABNpXZwxI','video','video','OneBanner Playthrough 250302','Embedded playthrough videos; duplicate automatic channel links excluded.');
INSERT INTO ih_resource VALUES('369','https://youtube.com/watch?v=d-5IMFzZSV4','video','video','One for Sorrow Overview, How to Play and Mini-playthrough','Embedded overview, how-to-play and mini-playthrough; automatic channel link excluded.');
INSERT INTO ih_resource VALUES('369','https://kevmakesgames.itch.io/one-for-sorrow','game_files','download_page','Itch.io','Itch.io game-files page; duplicate image link deduplicated.');
INSERT INTO ih_resource VALUES('370','https://drive.google.com/drive/folders/1Pvgf0jLD-yO3vgwjj38x7GPpzIFWxBMz?usp=sharing','game_files','folder','Valley of Gems 0.3.0-beta.1 Rules & Cards (Google Drive)','Rules and cards, version 0.3.0-beta.1.');
INSERT INTO ih_resource VALUES('370','https://www.youtube.com/watch?v=m554qdOKeag','video','video','https://www.youtube.com/watch?v=m554qdOKeag','Video URL declared in the first post.');
INSERT INTO ih_resource VALUES('371','https://drive.google.com/drive/folders/1eBlqG5X8X9LZqfXrRZ28yTLLmZMuah4X?usp=drive_link','game_files','folder','Maze Shift Rules 250119 / COLORS 250119 / MYTHICAL CREATURES 241228 / SPACE 250119','Folder listing rules and three themed Maze Shift versions.');
INSERT INTO ih_resource VALUES('371','https://youtube.com/watch?v=GRdC6O7nIuI','video','video','Maze Shift (In-Hand Moving Maze)','Embedded game and update videos; automatic channel links excluded.');
INSERT INTO ih_resource VALUES('371','https://youtube.com/watch?v=SjpPv9qtdgM','video','video','Maze Shift Update','Embedded game and update videos; automatic channel links excluded.');
INSERT INTO ih_resource VALUES('372','https://youtube.com/watch?v=nRPqEnVl68k','video','video','Hand-At-Arms - how to play and play through','Embedded how-to-play and printing-instructions videos; automatic channel links excluded.');
INSERT INTO ih_resource VALUES('372','https://youtube.com/watch?v=suCaOK332QY','video','video','Hand-At-Arms - no gutter fold PnP instructions','Embedded how-to-play and printing-instructions videos; automatic channel links excluded.');
INSERT INTO ih_resource VALUES('372','https://drive.google.com/drive/folders/1Bl552FZDNgj9fMm_kwtH6HTiW9j6Xh1z?usp=sharing','game_files','folder','All Files','Aggregate folder declared as all files.');
INSERT INTO ih_resource VALUES('372','https://drive.google.com/file/d/11VDrebuLZ_QbFVucxzKF-hDvBIbYy_2s/view?usp=drive_link','rules','file','Rulebook','Standalone rulebook.');
INSERT INTO ih_resource VALUES('372','https://drive.google.com/file/d/1rd-SFX47EpwOSePvqLoJ7BqPvbbN8GFd/view?usp=drive_link','rules','file','Almanac of Tips','Supplementary tips document.');
INSERT INTO ih_resource VALUES('372','https://drive.google.com/drive/folders/169A-GEMO57T6X0n5bG73sv4wL1iuWIbo?usp=drive_link','component','folder','Print and Play files','Print-and-play files folder.');
INSERT INTO ih_resource VALUES('372','https://playingcards.io/xazgdr','online_play','web_app','Public Room 1','Three public PlayingCards.io rooms.');
INSERT INTO ih_resource VALUES('372','https://playingcards.io/3tbqvm','online_play','web_app','Public Room 2','Three public PlayingCards.io rooms.');
INSERT INTO ih_resource VALUES('372','https://playingcards.io/36yhz3','online_play','web_app','Public Room 3','Three public PlayingCards.io rooms.');
INSERT INTO ih_resource VALUES('372','https://drive.google.com/file/d/14JE386Mo439DJS3DU_8Cn0erEVY5vZXo/view?usp=sharing','component','file','pcio file','PlayingCards.io setup file.');
INSERT INTO ih_resource VALUES('372','https://playingcards.io/game/standard-deck','online_play','web_app','PlayingCards.io','PlayingCards.io page declared with the online-play resources.');
INSERT INTO ih_resource VALUES('373','https://docs.google.com/document/d/1pfducMwkUEdHJl1BDJCjiTD5GIMGuwG8BsjQHHppB8s/edit?usp=sharing','rules','document','Rules Google Doc','Rules Google document.');
INSERT INTO ih_resource VALUES('373','https://drive.google.com/file/d/1zeAPuv00wu2MekPGWf5G_EXI13ZR6vlm/view?usp=drive_link','component','file','US letter size double-sided 3-7-2025','Double-sided US Letter build dated 2025-03-07.');
INSERT INTO ih_resource VALUES('373','https://playingcards.io/2pkch6','online_play','web_app','https://playingcards.io/2pkch6','PlayingCards.io room URL.');
INSERT INTO ih_resource VALUES('374','https://docs.google.com/document/d/1DyBgLmve-fy4rRgW6B3Rivz6j4A9jRoOeNLoUNqT_II/edit?tab=t.0','rules','document','Dive Into The Dungeon rules','Rules Google document.');
INSERT INTO ih_resource VALUES('374','https://drive.google.com/file/d/1bFWimT7jYofxdSAS7OxGU0CjJIuV3YIz/view?usp=sharing','component','file','Dive Into The Dungeon PnP file','Print-and-play file.');
INSERT INTO ih_resource VALUES('375','https://drive.google.com/drive/folders/1bGIEm890rSfK6bwsloV9QvGLRaJjB81y?usp=drive_link','game_files','folder','Cards and rules','Cards and rules; long-edge duplex instruction.');
INSERT INTO ih_resource VALUES('376','https://drive.google.com/drive/folders/1pOg7btFgpH9JtfbMexHvib2SF-Hrvmq4?usp=sharing','game_files','folder','RB-v1.0 and PnP files','Rulebook v1.0 and PnP files.');
INSERT INTO ih_resource VALUES('377','https://youtube.com/watch?v=_fRu1EHbHBw','video','video','Smuggler''s Sky: Hand of Fate - How to Play (PnP Solo Card Game) v2025.04','Embedded instructional videos; automatic channel links excluded.');
INSERT INTO ih_resource VALUES('377','https://youtube.com/watch?v=x2W2CJN43-Q','video','video','Smuggler''s Sky: Hand of Fate - Items & Black Market v2025.05','Embedded instructional videos; automatic channel links excluded.');
INSERT INTO ih_resource VALUES('377','https://www.youtube.com/watch?v=qEwM74osdCw','video','video','2 minute video showing how to cut and fold the pocketmod rulebook','Embedded instructional videos; automatic channel links excluded.');
INSERT INTO ih_resource VALUES('377','https://drive.google.com/drive/folders/1tJXjwf6rN9pFUN6N53ct6w2pzdhyirGy?usp=sharing','game_files','folder','Google Drive','Files available to download on Google Drive.');
INSERT INTO ih_resource VALUES('378','https://qu1rrel.itch.io/withering-grove','game_files','download_page','Game Files','Game files page.');
INSERT INTO ih_resource VALUES('378','https://playingcards.io/game/standard-deck','online_play','web_app','PlayingCards.io','PlayingCards.io version declared under ''To try the game''.');
INSERT INTO ih_resource VALUES('378','https://youtube.com/watch?v=bR0LrSDrAN0','video','video','WitheringGrove Playthrough 250209','Embedded playthrough; automatic channel link excluded.');
INSERT INTO ih_resource VALUES('379','https://drive.google.com/file/d/1rtoedYznrZETMN_JjfwwnY3t_mwbvn7e/view?usp=sharing','rules','file','here — rules','Files section: rules.');
INSERT INTO ih_resource VALUES('379','https://drive.google.com/file/d/1SAsm2Cjn1VvojGi9S4lE2nACmQ65K6Uy/view?usp=sharing','component','file','here — cards, colour version','Files section: colour cards.');
INSERT INTO ih_resource VALUES('379','https://drive.google.com/file/d/10gOHjFBmvM8EzHRXMSiudnX4-dh7zcRP/view?usp=sharing','component','file','here — cards, Low-ink/Grayscale version','Files section: low-ink/grayscale cards.');
INSERT INTO ih_resource VALUES('380','https://drive.google.com/drive/folders/1DGqAwFqMFnhySxv4ASj5HNhTuinIc-ZZ?usp=drive_link','game_files','folder','Google Drive folder','Project folder declared in the first post.');
INSERT INTO ih_resource VALUES('380','https://steamcommunity.com/sharedfiles/filedetails/?id=3424577600','online_play','workshop_module','Here!','Tabletop Simulator workshop version.');
INSERT INTO ih_resource VALUES('382','https://docs.google.com/document/d/1uJRTCk87gT6nfRoS6FhfvaA-zlVCAYk8a8rVxyq-8y8/edit?usp=share_link','rules','document','Rules','Rules Google document.');
INSERT INTO ih_resource VALUES('382','https://drive.google.com/file/d/13u2A0wHSaTMY5U1bKVNhowlEbXMbyK-d/view?usp=share_link','component','file','Low Ink WIP Build','Low-ink WIP build.');
INSERT INTO ih_resource VALUES('382','https://playingcards.io/dh86ak','online_play','web_app','PlayingCards.io','PlayingCards.io version.');
INSERT INTO ih_resource VALUES('383','https://buttonshygames.com/products/downtown-las-palmas','project_page','download_page','https://buttonshygames.com/products/downtown-las-palmas','Published product page linked from the withdrawn WIP.');
INSERT INTO ih_resource VALUES('383','https://youtube.com/watch?v=c42xgdU6yfM','video','video','Downtown Las Palmas Playthrough 11/25/2024','Embedded playthrough; automatic channel link excluded.');
INSERT INTO ih_resource VALUES('385','https://drive.google.com/file/d/1ivohyPSffZzbgYVJwiNCbgUETKTwobE8/view?usp=drive_link','rules','file','PMTIHG Rules (A4)','A4 rules.');
INSERT INTO ih_resource VALUES('385','https://drive.google.com/file/d/1_5AwYy37qwpGEdTMZwHx4VLvsRTLYXAe/view?usp=drive_link','component','file','PMTIHG Cards (A4 - print double sided, long edge)','A4 cards; double-sided long-edge printing.');
INSERT INTO ih_resource VALUES('385','https://drive.google.com/file/d/1L_627gKEFdOcEnk3Jr0P2TLeaha28-tB/view?usp=drive_link','rules','file','PMTIHG rules (Letter)','Letter rules.');
INSERT INTO ih_resource VALUES('385','https://drive.google.com/file/d/1T4JjJlsaV-st6FQNFAEUKluOwSHITOm3/view?usp=drive_link','component','file','PMTIHG cards (Letter - print double sided, long edge)','Letter cards; double-sided long-edge printing.');
INSERT INTO ih_resource VALUES('386','https://drive.google.com/file/d/1rW17Dbw5-V6R1OGzC1Hp4WVdynp6gqzW/view?usp=drive_link','rules','file','Rulebook','Rulebook.');
INSERT INTO ih_resource VALUES('386','https://drive.google.com/file/d/1ba1ANM62IERCIBZFlkLcrkXi3uEL0_Cy/view?usp=drive_link','component','file','Cards','Cards.');
INSERT INTO ih_resource VALUES('386','https://suno.com/song/6a0b8090-c473-45e8-baef-31174883f1af','video','web_app','Starcrossed: How to play song!','How-to-play song on Suno; provisional instructional-media classification.');
INSERT INTO ih_resource VALUES('387','https://drive.google.com/drive/folders/1IAvtRX36ViEt6BauY4rm0EVfKsHI5uJH','game_files','folder','HandMaze Files','HandMaze files; post notes that the rulebook was not ready.');
INSERT INTO ih_resource VALUES('389','https://drive.google.com/drive/folders/15i1yvl04FnPzmRTIj24DxBZXtrC3I9kf?usp=sharing','game_files','folder','Google Drive','Google Drive files folder.');
INSERT INTO ih_resource VALUES('390','https://drive.google.com/drive/folders/1ZNqLUWJ4HUH4Q0v1SpduALptfiRp3f1p?usp=sharing','component','folder','Components','Components folder.');
INSERT INTO ih_resource VALUES('392','https://drive.google.com/file/d/1DALYmtk22W-B5GbKlcqGZHc5ES9i_jht/view?usp=sharing','rules','file','PDF — Rulebook','Rulebook PDF.');
INSERT INTO ih_resource VALUES('392','https://drive.google.com/file/d/1ciEtyCZCv8T6NWSyROuzpJqPgA4s4FjM/view?usp=sharing','component','file','PDF — Cards','Cards PDF.');
UPDATE entries SET wip_thread_url=(SELECT wip_url FROM ih_entry i WHERE i.entry_id=entries.id) WHERE contest_id=12;
DELETE FROM entry_resource_scans WHERE checked_at='2026-09-11' AND entry_id IN (SELECT id FROM entries WHERE contest_id=12);
INSERT INTO entry_resource_scans(entry_id,checked_at,source_url,wip_status,resource_listing_status,notes) SELECT entry_id,'2026-09-11',COALESCE(wip_url,'https://boardgamegeek.com/thread/3378403/2025-in-hand-game-design-contest'),CASE WHEN wip_url IS NULL THEN 'not_found' ELSE 'found' END,listing_status,CASE listing_status WHEN 'observed' THEN 'Primo post renderizzato: anchor, link dinamici e media incorporati censiti; destinazioni non aperte.' WHEN 'none_declared' THEN 'Primo post renderizzato integralmente: nessun collegamento pertinente dichiarato osservato.' WHEN 'not_observable' THEN 'Post originale non osservabile; il primo messaggio residuo segnala un Google link ristretto senza esporne l’URL.' ELSE 'Nessun WIP effettivo individuato dopo verifica del roster ufficiale.' END FROM ih_entry;
INSERT OR IGNORE INTO remote_resources(game_id,kind,access_type,url,host,label,version_raw,availability_status,first_seen_at,last_verified_at) SELECT e.game_id,r.role,r.access_type,r.url,CASE WHEN instr(substr(r.url,instr(r.url,'//')+2),'/')>0 THEN substr(substr(r.url,instr(r.url,'//')+2),1,instr(substr(r.url,instr(r.url,'//')+2),'/')-1) ELSE substr(r.url,instr(r.url,'//')+2) END,r.label,NULL,'unknown','2026-09-11','2026-09-11' FROM ih_resource r JOIN entries e ON e.id=r.entry_id;
UPDATE remote_resources SET kind=(SELECT r.role FROM ih_resource r JOIN entries e ON e.id=r.entry_id WHERE e.game_id=remote_resources.game_id AND r.url=remote_resources.url),access_type=(SELECT r.access_type FROM ih_resource r JOIN entries e ON e.id=r.entry_id WHERE e.game_id=remote_resources.game_id AND r.url=remote_resources.url),label=(SELECT r.label FROM ih_resource r JOIN entries e ON e.id=r.entry_id WHERE e.game_id=remote_resources.game_id AND r.url=remote_resources.url),last_verified_at='2026-09-11' WHERE EXISTS(SELECT 1 FROM ih_resource r JOIN entries e ON e.id=r.entry_id WHERE e.game_id=remote_resources.game_id AND r.url=remote_resources.url);
DELETE FROM entry_resource_mentions WHERE entry_id IN (SELECT id FROM entries WHERE contest_id=12);
INSERT INTO entry_resource_mentions(entry_id,remote_resource_id,source_url,label_raw,content_role,is_primary,first_seen_at,last_seen_at) SELECT r.entry_id,rr.id,i.wip_url,r.label,r.role,CASE WHEN r.role='game_files' THEN 1 ELSE 0 END,'2026-09-11','2026-09-11' FROM ih_resource r JOIN ih_entry i ON i.entry_id=r.entry_id JOIN entries e ON e.id=r.entry_id JOIN remote_resources rr ON rr.game_id=e.game_id AND rr.url=r.url;
INSERT INTO remote_resource_observations(remote_resource_id,observed_at,evidence_url,observation_kind,availability_status,version_raw,notes) SELECT rr.id,'2026-09-11',i.wip_url,'declared_in_wip','not_checked',NULL,'Dichiarata nel primo post BGG; destinazione non aperta. Contesto: '||r.context||' Classificazione funzionale e tecnica provvisoria fino alla revisione completa del 2025.' FROM ih_resource r JOIN ih_entry i ON i.entry_id=r.entry_id JOIN entries e ON e.id=r.entry_id JOIN remote_resources rr ON rr.game_id=e.game_id AND rr.url=r.url WHERE NOT EXISTS(SELECT 1 FROM remote_resource_observations o WHERE o.remote_resource_id=rr.id AND o.observed_at='2026-09-11' AND o.evidence_url=i.wip_url AND o.observation_kind='declared_in_wip');
DROP TABLE ih_resource;
DROP TABLE ih_entry;
COMMIT;
