from collections import Counter
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
DATE = "2026-09-11"
CONTEST_IDS = (12, 14, 15, 22)
MATERIALS = []


def m(entry, kind, name, quantity, mode, context, level="required"):
    MATERIALS.append((entry, kind, name, name, quantity, level, mode, context))


# Roll & Write 2025 — requisiti espliciti del primo post.
m(793,"randomizer","dado","5 dadi","common","Components: 5 Dice")
m(793,"writing_tool","matita","1 per giocatore","common","Components: 1 Pencil p.p.")
m(793,"printable_component","plancia civiltà","1 per giocatore","printable","Components: 1 Civ Board p.p.")
m(794,"standard_deck","mazzo standard da 52 carte","1","common","uses a standard 52 card deck")
m(794,"writing_tool","penna o matita","1 per giocatore","common","a pen/pencil for each player")
m(794,"printable_component","mappa e foglio di riferimento","2–5 pagine","printable","Maps & Reference Sheet (2 - 5 pages)")
m(794,"printable_component","pacchetto avventura","4 pagine","printable","Adventure Pack 1: Kings (4 pages) OR Adventure Pack 2: Queens (4 pages)","alternative")
m(795,"printable_component","foglio di gioco","1 foglio A4","printable","The printed game sheet (on a single sheet of printed A4 paper)")
m(795,"randomizer","dado d6","2","common","Two D6 dice")
m(795,"writing_tool","penna o matita colorata","1 per giocatore","common","A coloured pen/pencil per player")
m(796,"printable_component","plancia","1 pagina","printable","1 Board (1 printed page) + 4D10 dice")
m(796,"randomizer","dado d10","4","common","1 Board (1 printed page) + 4D10 dice")
m(797,"printable_component","foglio stampato","2 per la prima partita","printable","Components Required: 2 printed sheets (for your first game... more required for the full game)")
m(797,"randomizer","dado d6","3","common","3 d6 dice")
m(797,"writing_tool","strumento per scrivere",None,"common","something to write with")
m(798,"randomizer","dado d6","1","common","1 d6 die")
m(798,"randomizer","dado colorato","4","specialized","4 color dice (red, blue, yellow, green, purple, orange)")
m(798,"writing_tool","matita colorata","6","common","6 colored pencils (red, blue, green, orange, purple, black)")
m(798,"printable_component","foglio giocatore","1 per giocatore","printable","4 different playersheets")
m(798,"writing_tool","matita","1 per giocatore","common","1 pencil per player")
m(799,"printable_component","foglio stampato fronte-retro","2","printable","Components: 2 Printed sheets (double-sided)")
m(799,"randomizer","dado d6","3","common","3 six-sided dice")
m(799,"writing_tool","penna o matita",None,"common","pen or pencil")
m(801,"randomizer","dado","3","common","3 dice")
m(801,"printable_component","foglio di gioco","1","printable","1 sheet")
m(802,"printable_component","carta opportunità","32","printable","Opportunity cards (32 pcs)")
m(802,"printable_component","carta token","14 per giocatore","printable","token cards (14/player)")
m(802,"printable_component","foglio punteggio","1 per giocatore","printable","score sheets (aka Thief Sheet) (1/player)")
m(802,"randomizer","set di dadi poliedrici","2 d4, 2 d6, 2 d8, 1 d10","specialized","dices (2 d4, 2 d6, 2 d8 and 1 d10)")
m(803,"printable_component","foglio giocatore",None,"printable","Player sheet")
m(803,"printable_component","carta obiettivo",None,"printable","Goal cards")
m(803,"randomizer","dado",None,"common","Dice will be used to create terrain and to populate it with animals.")
m(804,"randomizer","dado",None,"common","All you need to play this game is dice and a pen!")
m(804,"writing_tool","penna","1","common","All you need to play this game is dice and a pen!")
m(805,"randomizer","dado d6","4","common","Components needed are 4 D6")
m(805,"printable_component","foglio giocatore","1 per giocatore","printable","a player sheet ... for each player")
m(805,"writing_tool","penna o matita","1 per giocatore","common","a pen/pencil for each player")
m(807,"printable_component","foglio giocatore",None,"printable","Components - Player sheets 2.0")
m(807,"printable_component","carta parola","54","printable","54 word cards")
m(807,"writing_tool","matita","1","common","Pencil (quill & ink)")
m(809,"printable_component","plancia di gioco","1","printable","Components: Gameboard")
m(809,"randomizer","dado bianco","5","common","5 white dice")
m(809,"randomizer","dado di colore diverso","1","common","1 die of another color")
m(810,"printable_component","carte di gioco","oltre 100","printable","print and cut out over 100 cards")
m(810,"printable_component","foglio protagonista","1 per giocatore","printable","Each player has a Protagonist sheet")
m(810,"printable_component","carta scapolo","3 per giocatore","printable","3 Bachelor cards they can write on")
m(810,"printable_component","mazzo iniziale","11 carte per giocatore","printable","an 11 card starter deck")
m(810,"printable_component","carte obiettivo e incontro",None,"printable","Link to Objective and Encounter Cards")
m(811,"standard_deck","mazzo standard da 52 carte","1","common","Additional Components: Standard 52 Deck")
m(811,"writing_tool","matita o pennarello cancellabile","1 per giocatore","common","Pencil or Dry Erase Marker for each player")
m(813,"randomizer","dado d6","7","common","Components: 7 d6")
m(813,"token_marker","segnalino trasparente","7 per giocatore","specialized","7 markers (better if they are transparent) per player")
m(813,"printable_component","foglio giocatore","1 per giocatore","printable","One sheet per player")
m(814,"printable_component","foglio di marcatura","2","printable","2 Marking Sheets")
m(814,"randomizer","dado d6 comune","4","common","4 Common Dice (D6): Any Color can be used")
m(814,"randomizer","dado d6 di colore diverso","1","common","1 Common Dice (D6): Different color")
m(814,"printable_component","carta","24","printable","24 Cards (10 Blue Cards, 6 Red Cards and 8 Gray Cards)")
m(814,"token_marker","segnalino","4","supplied_or_printable","4 Markers: (2 Researchers and 2 Rats)")
m(815,"printable_component","pagina giocatore","1 per giocatore","printable","1 page per player")
m(815,"printable_component","pagina drago","1","printable","1 page for the dragon")
m(815,"randomizer","dado d6","2","common","Bring your own items: 2 D6 dice")
m(815,"token_marker","pedina giocatore","2","common","2 player-tokens")
m(816,"printable_component","foglio di gioco","1","printable","City Lights is ... played on a single sheet")
m(816,"randomizer","dado d6","3","common","3 six-sided dice")
m(816,"writing_tool","pennarello nero","1","common","1 black marker")
m(816,"writing_tool","pennarello colore caldo","1","common","1 warm colored marker (usually yellow)")
m(816,"writing_tool","pennarello colore freddo","1","common","1 cool colored marker (usually blue)")
m(817,"printable_component","plancia round","1","printable","1 round board")
m(817,"printable_component","carte gioco base","36","printable","36 cards for the base game")
m(817,"printable_component","carte espansione","7","printable","7 cards for the add-on", "optional")
m(817,"printable_component","foglio giocatore",None,"printable","player sheets")
m(817,"writing_tool","penna","1","common","Needed: pen")
m(817,"randomizer","dado d6","5","common","5 6-sided dice (4 regular, 1 special)")
m(818,"printable_component","foglio stampato","2","printable","Components: 2 Printed Sheets")
m(818,"writing_tool","penna","1","common","Components: ... Pen")
m(818,"randomizer","dado d6","2","common","Components: ... 2x D6")
m(818,"digital_device","telefono cellulare","1","digital_device","Components: ... Mobile Phone")
m(821,"randomizer","dado d6","6 per giocatore","common","Each player will need: 6 6-sided dice")
m(821,"printable_component","materiali papercraft o stampa 3D",None,"supplied_or_printable","Papercraft or 3D printed materials")
m(822,"printable_component","foglio principale e foglio pianeta","2","printable","print the Main Game Sheet, a Planet Sheet")
m(822,"writing_tool","matita","1","common","a pencil")
m(822,"randomizer","dado d6","1","common","a D6")
m(823,"printable_component","foglio di gioco","1","printable","Components: 1x Play sheet")
m(823,"randomizer","dado bianco","2","common","2x White Dice")
m(823,"randomizer","dado nero","2","common","2x Black Dice")
m(823,"randomizer","dado colorato","4 (rosso, verde, giallo, blu)","common","1x Red, Green, Yellow and Blue Dice")
m(823,"timer","timer","1","household","1x Timer (you can use your phone)")
m(824,"writing_tool","matita","1","common","Additional Components: Pencil")
m(824,"randomizer","dado","4, preferibilmente uno diverso","common","4 Dice (preferably 1 of a different colour)")
m(828,"printable_component","plancia 18×18","1","printable","The 18x18 gameboard")

# In-Hand 2025.
m(366,"printable_component","carta fronte-retro",None,"printable","cards are set up for duplex print")
m(367,"printable_component","carta incontro","14","printable","Components: 14 Encounter Cards")
m(367,"printable_component","carta cancello","1","printable","1 Gate Card")
m(367,"printable_component","carta negozio","1","printable","1 Shop Card")
m(367,"printable_component","carta personaggio","1","printable","1 Character Card")
m(367,"printable_component","carta salute","1","printable","1 Health card")
m(368,"printable_component","carta","16","printable","One Banner is a fully deterministic 16-card game")
m(369,"printable_component","carta","18","printable","18 cards: 13 Magpies, 4 Trees, 1 Spectre of Sorrows")
m(370,"printable_component","carta","18 + 2 boss","printable","18 cards (plus 2 additional Boss cards)")
m(371,"printable_component","carta labirinto","2 per puzzle","printable","Each puzzle is made up of two cards")
m(372,"printable_component","carta fronte-retro",None,"printable","all cards with bleed + left handed versions")
m(373,"printable_component","carta fronte-retro","27","printable","Components: 27 double-sided Cards")
m(373,"household_item","clip fermacarte mini","1","household","mini-sized binder clip")
m(373,"household_item","graffetta","5","household","5 paper clips")
m(375,"printable_component","carta","27","printable","Components: 27 cards")
m(377,"printable_component","carta missione","14","printable","Components: 14 Mission cards")
m(377,"printable_component","carte tracciamento","4","printable","1 Favor card, 1 Tracker card, 1 Credit card, 1 Inventory card")
m(378,"printable_component","carta","18","printable","Withering Grove is an 18-card game")
m(380,"printable_component","carte fronte-retro","45","printable","1 Round Tracker, 1 Cat, 6 Hazard Cards, 37 Stacks Cards")
m(380,"accessory","portacarte personalizzato a tre tasche","1","printable","1 Library Cart [custom 3-pocket card holder]")
m(380,"household_item","graffetta","1","household","1 Paperclip ... used to track Rounds")
m(380,"assembly_material","cartoncino o cartone 8×11","2 fogli","household","requires 2 blank 8×11 sheets of cardstock or cardboard", "required")
m(380,"assembly_tool","nastro trasparente",None,"household","Clear tape, scissors, and a ruler are also required for initial assembly")
m(380,"assembly_tool","forbici",None,"household","Clear tape, scissors, and a ruler are also required for initial assembly")
m(380,"assembly_tool","righello",None,"household","Clear tape, scissors, and a ruler are also required for initial assembly")
m(382,"printable_component","carta fronte-retro","18","printable","Components: 18 Cards - Front and back")
m(383,"printable_component","carta edificio fronte-retro","18","printable","Components: 18 Double-sided Building Cards")
m(385,"printable_component","mazzo di carte","29 da un pool di 45","printable","played using a deck of 29 cards (from an available pre-game pool of 45)")
m(387,"printable_component","carta","9 per giocatore","printable","Each player has 9 cards in their hand")
m(389,"printable_component","carta quadrata","30","printable","Components: 30 cards")
m(390,"printable_component","carta percorso","7","printable","Components: 7 Trail cards")
m(390,"printable_component","carta checkpoint","1","printable","1 Checkpoint card")
m(392,"printable_component","carta","18","printable","Components: 18 Cards")

# Children & Family 2025.
m(487,"printable_component","carta",None,"printable","Components, including: Cards")
m(487,"printable_component","tessera punteggio",None,"printable","Scoring Tiles")
m(488,"printable_component","tessera vita marina",None,"printable","Players will take turn flipping over two tiles")
m(488,"printable_component","carta tesoro","12","printable","If both players find all 12 treasures")
m(488,"token_marker","gettone tempo",None,"supplied_or_printable","take a time token")
m(489,"printable_component","carta","64","printable","Components: 64 cards")
m(490,"randomizer","dado personalizzato","3","supplied_or_printable","rolling 3 dice with Colors and Swirl Patterns")
m(490,"printable_component","tessera spirale","42 fronte-retro","printable","42 double sided swirly tiles")
m(491,"printable_component","materiali PnP",None,"printable","No components needed beyond the pnp files")
m(491,"printable_component","plancia giocatore",None,"printable","Optional player boards are also printable","optional")
m(494,"printable_component","carte gioco",None,"printable","Components and Rules")
m(494,"standard_deck","mazzo tradizionale",None,"common","A traditional deck will work for 2 players","alternative")
m(495,"randomizer","dado",None,"common","Roll and assign dice")
m(495,"printable_component","plancia esagonale","1","printable","hexagonal game board")
m(495,"token_marker","pedina ape",None,"supplied_or_printable","managing bees on a hexagonal game board")
m(496,"token_marker","pedina coniglio","12","supplied_or_printable","12x Bunny player pieces")
m(496,"printable_component","carte","98","printable","6 Character, 60 Move, 30 Momentum, 2 Momma/Bedtime Story cards")
m(496,"token_marker","pedina oggetto","3","supplied_or_printable","3x Item pieces")
m(496,"printable_component","plancia tracciaturno","1","printable","1x Turn Tracker Board")
m(496,"printable_component","plancia pista fronte-retro","3","printable","3x two-sided Racetrack Boards")
m(497,"printable_component","piattaforma finale","1","printable","Basic Components: Finishing platform")
m(497,"printable_component","supporto bonus","6","printable","6 Bonus Stands")
m(497,"token_marker","gettone salute","30","supplied_or_printable","30 Health tokens")
m(497,"printable_component","carta Chi",None,"printable","Chi-Cards")
m(497,"crafted_component","rana origami",None,"household","Craft a paper jumping frog")
m(498,"printable_component","plancia e carte",None,"printable","components required: the printed board and cards")
m(498,"randomizer","dado colorato","4 per giocatore","common","4 dice per player, preferably blue, red, yellow and green")
m(500,"printable_component","carta espressione","64","printable","Components: 64 expression cards")
m(501,"printable_component","carta gioco base","108","printable","88 Regular Cards and 20 Special Cards")
m(501,"token_marker","noce / gettone ghianda","50","supplied_or_printable","50 Nuts (Acorn Tokens)")
m(501,"household_item","monete, caramelle o fiches", "50","household","Use 50 coins, mints, candies, bingo chips ... in place of the Nuts","alternative")
m(502,"printable_component","carta nuvola","50","printable","Components needed: 50 cloud cards")
m(502,"printable_component","carta numero","5","printable","5 number cards")
m(502,"token_marker","gettone punto",None,"supplied_or_printable","tokens for points")
m(503,"printable_component","carta","28","printable","The game uses 28 cards")
m(503,"randomizer","dado","fino a 5","common","place up to 5 dice onto the available schools")
m(504,"printable_component","tessera isola",None,"printable","Components: Island Tiles")
m(504,"token_marker","pedina giocatore / meeple","6","common","6 Player Tokens ... I use meeples")
m(504,"household_item","pasta adesiva blu",None,"household","meeples with blue tac ... to help turn over cards","optional")
m(504,"printable_component","carta vita","18","printable","18 Life Cards")
m(504,"printable_component","carta risorsa","27","printable","7 Berries, 6 Knives, 6 Ropes, 8 Water Canteens")
m(505,"printable_component","plancia","1","printable","Components: 1 Board")
m(505,"printable_component","carta pesce","21","printable","21 Fish Cards")
m(505,"token_marker","gettone pesce","30","supplied_or_printable","30 Fish Tokens")
m(505,"token_marker","pedina sirena","4","supplied_or_printable","4 Mermaid Tokens")
m(505,"token_marker","pedina dinosauro","1","supplied_or_printable","1 Dinosaur Token")
m(505,"printable_component","carta primo giocatore","1","printable","1 First Player card")
m(506,"writing_tool","segnalino o penna","1","common","An additional marker or pen is required to play")
m(507,"printable_component","plancia esagonale","1 (37 esagoni)","printable","37 hex grid board")
m(507,"token_marker","pedina","6 in 2 colori","common","6 pawns in 2 different colors")
m(507,"token_marker","tessera ghiaccio / pietra","37","common","37 ice tiles ... use checkers, meeples, etc","alternative")
m(508,"printable_component","carta","62","printable","Components: 62 cards")
m(508,"printable_component","tessera bonus passaggio","6","printable","6 passing bonus tiles")
m(508,"token_marker","miniatura cioccolato","13","specialized","13 chocolate minis")
m(508,"printable_component","tracciato limite collettivo","1","printable","1 collective limit track")
m(508,"token_marker","segnalino limite collettivo","1","common","1 collective limit marker")
m(508,"household_item","cubetto o disco di legno",None,"household","wooden cubes or discs will work fine","alternative")
m(509,"printable_component","plancia","1","printable","Components: 1 board")
m(509,"token_marker","gettone foglia","15","supplied_or_printable","15 leaf tokens")
m(509,"token_marker","pedina giocatore","2–4","supplied_or_printable","2–4 player tokens")
m(509,"randomizer","dado d6","1","common","1 regular die (D6)")
m(510,"randomizer","dado d6","molti, preferibilmente 3 colori","common","requires 6 sided dice ... preferably lots of dice ... three different colors")
m(510,"scoring_tool","plancia cribbage","1","household","A cribbage board can be useful to keep score","optional")
m(510,"household_item","foglio di carta","1","household","or just use a piece of paper","alternative")
m(510,"token_marker","gettone colorato o fiche poker",None,"household","Colored tokens or different color poker chips ... track bets")
m(511,"printable_component","carta prompt","20","printable","20 prompt cards")
m(511,"printable_component","foglio da disegno","1 per giocatore","printable","Drawing sheets (1 per player)")
m(511,"writing_tool","matita o penna","1 per giocatore","common","Pencil or Pen (1 per player)")
m(511,"token_marker","gettone punto","3","supplied_or_printable","3 Point Tokens")
m(511,"randomizer","dado d6","1","common","6-sided dice")
m(511,"printable_component","foglio punteggio","1","printable","Score sheet")
m(513,"printable_component","plancia parco","4","printable","4 amusement park player boards")
m(513,"printable_component","plancia round","1","printable","1 round board")
m(513,"printable_component","carte","115","printable","90 attraction, 10 action, 15 planning cards")
m(513,"token_marker","meeple visitatore","100","specialized","100 visitor meeples")
m(513,"token_marker","segnalino giocatore","4","common","4 player markers")
m(513,"token_marker","segnalino round","1","common","1 round marker")
m(513,"token_marker","segnalino primo giocatore","1","common","1 first player marker")

# 1-Card 2025.
m(514,"printable_component","carta formato poker","1","printable","[1] - Póker size card")
m(514,"randomizer","dado d6","10 (4 rossi, 4 blu, 1 viola, 1 giallo)","common","[10] - D6 dice : 4 Red, 4 Blue, 1 Purple, 1 Yellow")
m(514,"token_marker","cubetto","9 (1 rosso, 4 blu, 4 gialli)","common","[9] - Cubes : 1 Red, 4 Blue, 4 Yellow")
m(516,"printable_component","carta labirinto","1","printable","a 2+ player one-card maze-race")
m(517,"printable_component","carta personalizzata","1","printable","1 custom card or a 6 of Hearts")
m(517,"standard_deck","sei di cuori","1","common","1 custom card or a 6 of Hearts","alternative")
m(518,"printable_component","carta fronte-retro","1","printable","Components: 1 card (both sides)")
m(518,"randomizer","dado d6 di colori diversi","2","common","2d6 of different colors")
m(518,"accessory","bustina protettiva","1","common","It's recommended to use a sleeve for the card","optional")
m(518,"writing_tool","pennarello cancellabile","1","common","you can use a dry-erase marker to better visualize the elements","optional")
m(520,"printable_component","carta camion","1","printable","Components: Truck card")
m(520,"timer","cronometro o timer","1","household","Stopwatch/Timer")
m(520,"household_item","piccolo oggetto casuale","20","household","20 random small items, no bigger than a d20")
m(520,"token_marker","segnalino partenza e arrivo","1","common","A marker for start and finish")
m(520,"printable_component","foglio punteggio","1","printable","Score sheet")
m(522,"printable_component","carta Snaked!","1","printable","1 Snaked! Card")
m(522,"standard_deck","carta qualsiasi","1","common","the game can be played with any card","alternative")
m(524,"printable_component","carta","1","printable","Components: 1 card")
m(525,"randomizer","dadi nascosti",None,"common","battling your hidden dice against your opponent","unclear")
m(526,"printable_component","carta fronte-retro","1","printable","Components: 1x Card")
m(526,"token_marker","cubetto blu","1","common","1x Blue Cube (Dragonfly)")
m(526,"token_marker","cubetto giallo pieno","1","common","1x Solid Yellow Cube (Honeybee)")
m(526,"token_marker","cubetto giallo trasparente","20","specialized","20x Clear Yellow Cubes (Pollen)")
m(526,"randomizer","dado d6","2","common","2x D6 Dice (Honeybee Movement)")
m(527,"printable_component","carta hovercraft","1","printable","1x Hovercraft Card")
m(527,"printable_component","foglio di riferimento","1","printable","1x Rulebook w/ Reference Sheet")
m(527,"token_marker","cubetto tracciatore blu 8 mm","2","specialized","2x 8mm blue tracker cubes")
m(527,"randomizer","dado d6 rosso 16 mm","9","specialized","9x red 16mm d6 mine dice")
m(527,"randomizer","dado d6 arancione 16 mm","3","specialized","3x orange 16mm d6 mine dice")
m(527,"randomizer","dado d6 verde 16 mm","6","specialized","6x green 16mm d6 alligator dice")
m(527,"randomizer","dado d6 bianco 16 mm","1","specialized","1x white 16mm d6 fire-extinguisher die")
m(527,"randomizer","dado d12","1","common","1x d12 gasoline die")
m(528,"printable_component","carta di gioco","1","printable","In The Trench is a micro tactical battle card game")
m(528,"printable_component","carta tracciamento punti vita","1","printable","A Track HP card has been added")
m(528,"token_marker","gettone unità",None,"supplied_or_printable","along with the unit tokens")
m(529,"printable_component","carta formato poker","1","printable","Components: 1x Poker Size Card")
m(529,"household_item","clip fermadocumenti o graffetta","1","household","1x document clip (or paper clip)")
m(529,"randomizer","dado d6","1","common","1x D6 dice")
m(529,"token_marker","piccolo segnalino","12 (2 per ciascuno di 6 colori)","common","12x small markers ... two markers in each of six different colors")
m(530,"printable_component","carta di gioco","1","printable","The Laced Up game card")
m(530,"household_item","laccio da scarpa o cordino","2 di colori diversi","household","Two differently coloured shoelaces, or string")
m(531,"printable_component","carta","1","printable","Components: 1 Card (one-sided)")
m(531,"randomizer","dado d6 da 12 mm","9–10","common","9-10 six-sided dice (12mm)")
m(532,"randomizer","dado d6","2","common","LUCKY 4 WORDS REQUIRES: Two D6 dice")
m(532,"writing_tool","pennarello cancellabile","2 di colori diversi","common","two dry erase markers")
m(532,"randomizer","dado d6","1","common","LUCKY LETTERS REQUIRES: One D6 die")
m(532,"writing_tool","pennarello cancellabile","1","common","a dry erase marker")
m(533,"printable_component","carta fronte-retro","1","printable","Components: 1 double-sided card")
m(534,"printable_component","carta fortezza","1","printable","Set the fortress card in its OUT position")
m(534,"randomizer","dado d4 azione","2","common","Roll the 2 Action Dice (d4)")
m(534,"token_marker","cubetti colorati",None,"common","Place all the colored cubes on their respective positions","unclear")
m(535,"printable_component","carta","1","printable","Components: 6 dice ... and 1 card")
m(535,"randomizer","dado bianco 16 mm","3","common","6 dice (3 white + 3 black) 16mm size")
m(535,"randomizer","dado nero 16 mm","3","common","6 dice (3 white + 3 black) 16mm size")
m(536,"printable_component","carta campo di battaglia","1","printable","components: 1 battle ground card")
m(536,"randomizer","dado rosso","5","common","5 red dice")
m(536,"randomizer","dado blu","5","common","5 blue dice")
m(536,"randomizer","dado bianco","5","common","5 white dice")
m(537,"printable_component","carta PnP","1","printable","PnP Card")
m(537,"randomizer","dado d20","1","common","track the Guard's Health (d20)","alternative")
m(537,"randomizer","dado d8","2","common","your Focus (d8), and ... Attack location (d8)","alternative")
m(537,"digital_device","companion web per dadi","1","digital_device","Dice Companion Web App","alternative")
m(538,"printable_component","carta","1","printable","Components: 1 card")
m(538,"randomizer","dado in quattro colori","20 (5 per colore)","common","20 dice (5 of each 4 colours)")
m(539,"printable_component","carta formato poker fronte-retro","1","printable","1 poker size card (2 sided)")
m(539,"randomizer","dado d6","6","common","6x D6 dice")
m(540,"printable_component","carta fronte-retro","1","printable","Components: 1 card (two sided)")
m(540,"randomizer","dado","1","common","Components: ... 1 die")
m(541,"printable_component","carta fronte-retro","1","printable","Components: 1 card (two sided)")
m(541,"household_item","torta o sua porzione","1","household","The aim of the game is to steal the cake ... The cake is kept somewhere known","unclear")
m(542,"printable_component","carta formato poker","1","printable","Components: 1 Card (Poker Size)")
m(542,"randomizer","dado d6 colorato","5","common","5 Colored Dice (d6)")
m(543,"printable_component","carta fronte-retro","1","printable","Component Description: 1 Double-Sided Card")
m(544,"printable_component","carta buffet","1","printable","1 open buffet card")
m(544,"randomizer","dado","4","common","4 dice (any color)")
m(544,"token_marker","meeple","16 (4 per 4 colori)","common","16 meeples (4 red, 4 black, 4 green, 4 white)")
m(544,"token_marker","cubetto","4 (1 per colore giocatore)","common","4 cubes (1 in each player's color)")
m(545,"printable_component","carta","1","printable","Components: 1 card")
m(545,"randomizer","dado d6","2","common","2 D6 dice")
m(545,"token_marker","gettone telecamera","5","supplied_or_printable","5 tokens for camera")
m(545,"token_marker","gettone opera d'arte","5","supplied_or_printable","5 tokens for work of art")
m(545,"token_marker","gettone giocatore","3","supplied_or_printable","3 tokens for players")
m(546,"printable_component","carta astronave","1","printable","List of Components: 1 spaceship card")
m(546,"token_marker","membro equipaggio identificabile","10","common","10 crewmembers (anything that fits on the card and is easily identifiable works)")
m(546,"token_marker","gettone compito o sabotaggio","5","common","5 task/sabotage tokens (ie. cubes)")
m(546,"writing_tool","strumento per annotazioni","1 per giocatore","common","Note taking tools for both players")
m(547,"printable_component","carta","1","printable","Components: 1 card")
m(547,"randomizer","dado d6","2","common","2 D6 dice")
m(547,"token_marker","gettone giocatore","6 in 2 colori","supplied_or_printable","6 tokens of 2 colors (3 for each player)")
m(547,"token_marker","gettone cibo","8","supplied_or_printable","8 tokens of food")
m(547,"token_marker","gettone avanzamento","2","supplied_or_printable","2 tokens for track of progress")
m(548,"printable_component","carta","1","printable","Components: 1 card")
m(548,"household_item","cordino","2 distinguibili","household","2 strings (yarn, twine, cord, wire, ribbon, shoe laces,...)")
m(548,"assembly_material","carta robusta o cartone",None,"household","glue it on strong paper or cardboard","alternative")
m(548,"assembly_material","colla",None,"household","glue it on strong paper or cardboard","alternative")
m(549,"printable_component","carta fronte-retro","1","printable","Components: 1 Card (two-sided for variations)")
m(550,"token_marker","meeple","2","common","Components: 2 meeple pieces")
m(550,"household_item","matita usata come bacchetta","4","household","4 pencils (optional – use as chopsticks for challenge mode!)","optional")
m(550,"randomizer","dado d6","2","common","2 dice (D6)")
m(550,"token_marker","cubetto marrone","8","common","8 brown cubes")
m(550,"token_marker","cubetto verde","2","common","2 green cubes")
m(550,"token_marker","cubetto giallo","5","common","5 yellow cubes")
m(550,"printable_component","segmento ponte","4 da una carta","printable","1 card cut into 4 bridge segments")
m(550,"household_item","tavolo o superficie piana","1","household","A table or flat surface")
m(550,"assembly_material","vecchia carta da gioco e colla",None,"household","glueing them onto an old card","optional")
m(550,"assembly_material","nastro adesivo o laminazione",None,"household","sticky tape or laminate","optional")

assert len({(e,k,n,q,l) for e,k,n,_,q,l,_,_ in MATERIALS}) == len(MATERIALS)


def q(value):
    return "NULL" if value is None else "'" + str(value).replace("'", "''") + "'"


sql = ["-- Declared gameplay materials from first posts only; rules were not opened or downloaded.",
       "PRAGMA foreign_keys=ON;", "BEGIN IMMEDIATE;",
       "CREATE TEMP TABLE dm(entry_id,material_kind,name_normalized,name_raw,quantity_raw,requirement_level,supply_mode,context_raw);"]
for row in MATERIALS:
    sql.append("INSERT INTO dm VALUES(" + ",".join(q(v) for v in row) + ");")
ids = ",".join(map(str, CONTEST_IDS))
sql += [
    f"DELETE FROM entry_material_requirements WHERE entry_id IN (SELECT id FROM entries WHERE contest_id IN ({ids}));",
    "INSERT INTO entry_material_requirements(entry_id,material_kind,name_normalized,name_raw,quantity_raw,requirement_level,supply_mode,context_raw,source_url,first_seen_at,last_seen_at) SELECT d.entry_id,d.material_kind,d.name_normalized,d.name_raw,d.quantity_raw,d.requirement_level,d.supply_mode,d.context_raw,e.wip_thread_url,'2026-09-11','2026-09-11' FROM dm d JOIN entries e ON e.id=d.entry_id;",
    f"DELETE FROM entry_material_scans WHERE checked_at='2026-09-11' AND coverage_scope='first_post_only' AND entry_id IN (SELECT id FROM entries WHERE contest_id IN ({ids}));",
    f"INSERT INTO entry_material_scans(entry_id,checked_at,source_url,wip_status,material_listing_status,coverage_scope,notes) SELECT e.id,'2026-09-11',COALESCE(e.wip_thread_url,e.entry_url),CASE WHEN e.wip_thread_url IS NULL THEN 'not_found' ELSE 'found' END,CASE WHEN e.id IN (391,521) THEN 'not_observable' WHEN e.wip_thread_url IS NULL THEN 'not_checked' WHEN EXISTS(SELECT 1 FROM dm WHERE dm.entry_id=e.id) THEN 'observed' ELSE 'none_declared' END,'first_post_only',CASE WHEN e.id IN (391,521) THEN 'Post originale non osservabile; nessun requisito inventato.' WHEN e.wip_thread_url IS NULL THEN 'WIP non individuato; la voce di roster non sostituisce il primo post.' WHEN EXISTS(SELECT 1 FROM dm WHERE dm.entry_id=e.id) THEN 'Materiali di gioco esplicitamente dichiarati nel primo post; le regole non sono state aperte né scaricate.' ELSE 'Nessun requisito materiale sufficientemente esplicito osservato nel primo post; le regole potranno integrare il censimento.' END FROM entries e WHERE e.contest_id IN ({ids});",
    "DROP TABLE dm;", "COMMIT;"
]
(ROOT / "catalog" / "2025-declared-materials.sql").write_text("\n".join(sql)+"\n",encoding="utf-8")

counts = Counter(row[0] for row in MATERIALS)
md = ["# Materiali di gioco dichiarati nei primi post — contest 2025", "",
      "Rilevazione dell’11 settembre 2026 limitata al primo post renderizzato dei WIP di Roll & Write, In-Hand, Children & Family e 1-Card. I regolamenti esterni non sono stati aperti o scaricati: l’inventario è quindi esplicitamente integrabile in seguito.", "",
      "Le categorie sono provvisorie. `printable_component` indica elementi di gioco descritti come stampabili; le altre categorie distinguono randomizzatori, strumenti di scrittura, mazzi standard, segnalini, oggetti domestici, accessori, strumenti di montaggio e dispositivi digitali.", "",
      "| Entry ID | Requisiti distinti |", "|---:|---:|"]
for entry_id in sorted(counts): md.append(f"| {entry_id} | {counts[entry_id]} |")
md += ["", "## Evidenze", "", "| Entry ID | Categoria provvisoria | Materiale normalizzato | Quantità dichiarata | Obbligatorietà | Approvvigionamento | Evidenza originale |", "|---:|---|---|---|---|---|---|"]
for e,k,n,raw,qty,level,mode,ctx in MATERIALS:
    clean=lambda x: "" if x is None else str(x).replace("|","/").replace("\n"," ")
    md.append(f"| {e} | `{k}` | {clean(n)} | {clean(qty)} | `{level}` | `{mode}` | {clean(ctx)} |")
md += ["", "## Limiti", "", "- Le quantità e i nomi sono quelli dichiarati o prudentemente raggruppati nel primo post.", "- Nessun requisito è stato dedotto da una meccanica quando il materiale non era dichiarato con sufficiente chiarezza.", "- `none_declared` significa soltanto che il primo post non espone un requisito sufficientemente esplicito; non certifica che il gioco non richieda materiali.", "- Una futura lettura dei regolamenti potrà aggiungere, correggere o dettagliare l’inventario senza sovrascrivere questa provenienza."]
(ROOT / "sources" / "2025-DECLARED-MATERIALS.md").write_text("\n".join(md)+"\n",encoding="utf-8")
print(f"generated {len(MATERIALS)} material requirements across {len(counts)} entries")
