from collections import Counter
from pathlib import Path
from urllib.parse import urlparse
ROOT=Path(__file__).resolve().parents[1]; DATE='2026-09-15'; CONTEST_ID=16
DATA=[
(552,'Florek & Florka','3454362','observed'),(553,'Enchanted Forest Solo Variant','3406119','observed'),(554,'Sabi','3466096','observed'),(555,'Humanoid Monsters Have Brains','3471610','observed'),(556,'War Against the Chtorr - Psionic Corps','3471614','observed'),(557,'Junk Punk','3446309','observed'),(558,'Unfinished Window','3350683','observed'),(559,'The Wily Widow','3455165','observed'),(560,'Solo Automa for Avignon','3472563','observed'),(561,'The Bus Conspiracy','3445556','observed'),(562,'Veteran Solo Mode','3418473','observed'),(563,'Midnight Racetrack','3472592','observed'),(564,'Lone Digger','3474645','observed'),(565,'Codenames Rush','3475523','none_declared'),(566,'boop. Solo Mode','3478437','observed'),(567,'Bot Families','3480600','observed'),(568,'Full Auto','3483643','observed'),(569,'Solisauron','3486373','not_observable'),(570,'b-AI-rista','3490914','observed'),(571,'Felipe I / Felipe II','3490911','observed'),(572,'Forest Link','3496730','observed'),(573,'Cathy','3327279','observed'),(574,'Malakar','3398741','observed'),(575,'Shrimpy','3502388','observed'),(576,'SUPERCAT','3425290','observed'),(577,'Unofficial Automa for Deep Regrets','3503201','observed'),(578,'Nemesis','3504827','observed'),(579,'Grandma & Grandpa','3511290','observed'),(580,'Unofficial Solo Mode & Campaign Mode','3385154','observed'),(581,'YRO Solo Campaign','3422271','observed'),(582,'Throne Alone','3383061','observed'),(583,'M. KloneUs','3511300','observed'),(584,'Pharaoh Code Solo Mode',None,'not_checked'),(585,"Lord d'Automa",'3512047','observed'),(586,'Splendor Solo Mode',None,'not_checked'),(587,'Cavemono','3344024','observed'),(588,'Up Front Browser Automa','3512452','observed'),(589,'RuneBot','3510981','observed')]
R=[]
def a(e,role,form,context,*pairs):
 for u,l in pairs:R.append((e,u,role,form,l,context))
def bgg(p):return 'https://boardgamegeek.com'+p
a(552,'online_play','workshop_module','TTS indicato per provare il gioco base e la variante.',('https://steamcommunity.com/sharedfiles/filedetails/?id=2413052884','TTS'))
a(552,'rules','bgg_file','Pacchetto PDF e PNG.',(bgg('/filepage/296490/florek-and-florka-the-automas-artificial-opponents'),'Download rulebook package (PDF + PNG)'))
a(553,'rules','document','Versioni corrente e storiche.',('https://docs.google.com/document/d/1GukDC9HkRbdkeLaCgFk1oCFbfyzk8R3w8LTv2G5_Mug/edit?usp=sharing','Version 3'),('https://docs.google.com/document/d/1Cz-Dw_9B7_vCulIX0W8C718YP4K7yAexAshyqGlfYho/edit?usp=sharing','version 2'),('https://docs.google.com/document/d/1P7NAZHlbUXtupoYEYxHaCMzmi4hzkTXmTPDBPI6Pg-I/edit?usp=sharing','version 1'),(bgg('/thread/3406119/article/45891618#45891618'),'solo variant mockup'))
a(554,'rules','file','Regole PDF.',('https://drive.google.com/file/d/11hhBp7RJ5toQAx_QSBG_ENMR800Az5F1/view?usp=sharing','downloaded here'))
a(555,'game_files','bgg_file','Regole e carte.',(bgg('/filepage/296114/2025-solomode-contest-my-solo-mode-for-quest-for-t'),'rules and cards'))
a(556,'game_files','bgg_file','Regole e carte.',(bgg('/filepage/296126/2025-solomode-contest-my-solo-mode-for-warfighter'),'rules and cards'))
a(557,'rules','bgg_file','File dell’automa.',(bgg('/filepage/317610/solo-mode-junk-punk'),'solo automa'))
a(558,'rules','document','Versioni delle regole.',('https://docs.google.com/document/d/1NqXSTtlYbg_i6xLOpORzNijOClKOMCNJDpIOO2m_jFc/edit?usp=sharing','version 4.1'),('https://docs.google.com/document/d/1GD2aBYuZ0fEi6TWcp6tVan3z7s5DcxuxWfT4octg1fc/edit?usp=sharing','version 1'),('https://docs.google.com/document/d/1U4Jv94L4EcAx9aSBb5Gdlkoja9--yAfPO1Zu-Bfb7TY/edit?usp=sharing','version 2'),('https://docs.google.com/document/d/1-9q8z7xTF9Fn2rFIRYeV3WtpdTA_s6RCdfjTKrt3a_c/edit?usp=sharing','version 3'),('https://docs.google.com/document/d/1_HjdEkvOhbhxCuqzXuGvv756r-e9EnihqHGr18P1uKk/edit?usp=sharing','version 4'))
a(558,'player_aid','document','Aiuto giocatore.',('https://docs.google.com/document/d/1Sr0FBofNALlDa_P3O8Locv2SYomx8j0k/edit?usp=sharing&ouid=106836397923669534161&rtpof=true&sd=true','player aid created by Anke'))
a(559,'rules','bgg_file','Regole.',(bgg('/filepage/301437/the-wily-widow-a-deadly-dowagers-solomode'),'Rules PDF'))
a(559,'online_play','web_app','Piattaforme indicate per il playtest.',('https://tabletopia.com/games/deadly-dowagers','Tabletopia'),('https://steamcommunity.com/sharedfiles/filedetails/?id=3211478551','Tabletop Simulator'))
a(559,'video','video','Video panoramica; canale automatico escluso.',('https://youtube.com/watch?v=crRQPQILJ1s','Deadly Dowagers - In Focus'))
a(560,'rules','document','Regole correnti.',('https://docs.google.com/document/d/1rTuHtpetJ5OFfJoWmXKl1h4EWRINy02f63ZAxgEOve8/edit?tab=t.0#heading=h.dwlaadsewinq','Automa Rules'))
a(561,'project_page','download_page','Pagina indicata per PDF e formattazione.',('https://talkingshelfspace.com/extras/','talkingshelfspace.com/extras'))
a(562,'project_page','download_page','Pagina indicata per la variante.',('https://talkingshelfspace.com/extras/','talkingshelfspace.com'))
a(563,'rules','file','Regole PDF.',('https://drive.google.com/file/d/14bALQUgEPogJfBcQktP6zhksxoVH6Jnz/view?usp=sharing','here'))
a(564,'rules','document','Regole.',('https://docs.google.com/document/d/11lRF-IbilykUjsqydeUNkma6dvx9y_ArNW5R93FjfAc/edit?usp=sharing','Google Drive'))
a(566,'rules','bgg_article','Seconda revisione nel thread.',(bgg('/thread/3478437/article/45813015#45813015'),'second revision'))
a(567,'rules','bgg_file','Regole della variante.',(bgg('/filepage/297062/du-plessis-de-winter-et-les-autres-familles-bot-fa'),'bot families'))
a(568,'rules','bgg_file','Versione 7A corrente.',(bgg('/filepage/304242/joyride-full-auto-rules-for-self-driving-cars-allo'),'most recent version'))
a(568,'rules','file','Versioni Google Drive.',('https://drive.google.com/file/d/1xdXJKOZiTLJJVyT1OBocTpM_HCX9FcuK/view?usp=sharing','Version 7'),('https://drive.google.com/file/d/1cLGe0nRS1_xRLsypP3SnXeV1l-V7hMn6/view','rules'))
a(568,'video','video','How-to-play.',('https://youtube.com/watch?v=O1HNQfoTW94','How to Play JOYRIDE Solo'))
a(568,'supporting_page','bgg_thread','Discussione e resoconto.',(bgg('/thread/3401491/solo-mode'),'development thread'),(bgg('/thread/3474388/solo-play-through-against-3-bots-using-the-full-au'),'session report'))
a(570,'game_files','bgg_file','Regole e mazzo automa.',(bgg('/filepage/297774/unofficial-solo-variant-coffee-rush-against-b-ai-r'),'rules and automa deck'))
a(571,'game_files','bgg_file','Href troncato conservato esattamente.',(bgg('/filepage/297776/unofficial-solo-va'),'files section'))
a(572,'rules','file','Regolamento.',('https://drive.google.com/file/d/1i2K2-GTKHHpc6p609VY4ffJI9Zmgnz8G/view?usp=sharing','Rules document'))
for e,folder,v1,v2 in [(573,'https://drive.google.com/drive/folders/18qVcYBCT6E_lvcNNp5bW_1CKP8lTB1uZ?usp=sharing','https://youtube.com/watch?v=Me0Qxohb-BY','https://youtube.com/watch?v=E8fmc2d99so'),(574,'https://drive.google.com/drive/folders/1RCm_Ry4_4BjGlaMGgfEPE5FnhfZdNykK','https://youtube.com/watch?v=tlDbskiW9TU','https://youtube.com/watch?v=OamzD4SFUZQ')]:
 a(e,'game_files','folder','Regole e mazzo solo.',(folder,'Unofficial Solo Mode'));a(e,'video','video','How-to-play e playthrough; canali esclusi.',(v1,'How to play'),(v2,'Playthrough'))
a(575,'video','video','Video del gioco base dichiarato come supporto.',('https://www.youtube.com/watch?v=jSfY3jeY278','how to play MANTIS'))
a(575,'rules','bgg_file','Regole automa.',(bgg('/filepage/299322/mantis-automa-shrimpy'),'Download the PDF'))
a(576,'game_files','file','Regole e aiuti sperimentali.',('https://github.com/okonomichiyaki/supercat/releases/download/v0.10/SUPERCAT-base-rules.pdf','latest version v0.10'),('https://github.com/okonomichiyaki/supercat/releases/download/v0.10/SUPERCAT-base-player-aid.pdf','experimental player aid'),('https://github.com/okonomichiyaki/supercat/releases/download/v0.10/SUPERCAT-base-action-cards.pdf','experimental action card deck'))
a(576,'supporting_page','bgg_article','Istruzioni e discussione.',(bgg('/thread/3425290/article/46008535#46008535'),'player aid instructions'),(bgg('/thread/3425290/article/46121480#46121480'),'action card instructions'),(bgg('/thread/3499164/supercat-a-procedural-non-player-system-for-solo-b'),'supporting thread'))
for e,p,l in [(577,'/filepage/298450/unofficial-automa-for-deep-regrets','version 2.1'),(578,'/filepage/299328/nemesis-elysium-solobot','Link to the PDF'),(579,'/filepage/296317/unofficial-solo-variant','Unofficial Solo Variant'),(580,'/filepage/287495/unofficial-solo-mode-and-campaign-v10','V.1.0')]:a(e,'rules','bgg_file','Regole della variante.',(bgg(p),l))
a(581,'rules','bgg_file','Versioni inglese e tedesca.',(bgg('/filepage/291216'),'English Version'),(bgg('/filepage/291217'),'German Version'))
a(582,'rules','bgg_file','Regole.',(bgg('/filepage/301489/castle-combo-throne-alone-solo-mode-rules'),'file section'))
a(582,'video','video','Playthrough inglese e tedesco.',('https://youtu.be/XQ78uuQ-Bfo','German playthrough'),('https://youtu.be/YrZLSaKWFhc','English playthrough'))
a(583,'rules','bgg_file','PDF.',('https://boardgamegeek.com/filepage/300400/2025-solomode-m-kloneus','PDF'))
a(585,'rules','document','Regole.',('https://docs.google.com/document/d/1u0cRjgeagJr1cFnBHGmt9Fl2rz1qJPtjqvoi-2EQJlY/edit?usp=sharing','Full rules here'))
a(587,'component','file','Carte PnP.',('https://drive.google.com/file/d/1OAd1-nuHZLVXWjAz-MGRueD9Pe37fBbp/view?usp=drive_link','PnP Cards v0.1'))
a(587,'rules','file','Regolamento.',('https://drive.google.com/file/d/1NSSRRBLpG68LvIpalyL8U16FB8nPNPNf/view?usp=drive_link','Rulebook v0.2'))
a(588,'online_tool','source_repository','Repository dell’applet browser.',('https://github.com/bsturk/up_front_bot','up_front_bot'))
a(589,'game_files','folder','Regole e due fogli carte.',('https://drive.google.com/drive/folders/1LD-mUpN6VArPUGob20eEGmwLBxdmJbLi?usp=sharing','rules file and two card sheets'))
a(589,'audio','file','Panoramica podcast.',('https://drive.google.com/file/d/1e7vekARsFQVj3wV53OFNOxGsHH_sA3MV/view?usp=sharing','podcast overview'))
a(589,'rules','document','Versione originale a otto carte.',('https://docs.google.com/document/d/1TkmzgoSoo09hn0Q0r6l59iAwPMhHIChO/edit?usp=drivesdk&ouid=116225575084141017501&rtpof=true&sd=true','Original 8 card bot'))
assert len(DATA)==38 and len({(e,u) for e,u,*_ in R})==len(R)
def q(v):return 'NULL' if v is None else "'"+str(v).replace("'","''")+"'"
sql=['-- Solomode 2025 first-post resources; external destinations were not opened.','PRAGMA foreign_keys=ON;','BEGIN IMMEDIATE;','CREATE TEMP TABLE sm_e(id PRIMARY KEY,title,wip,status);','CREATE TEMP TABLE sm_r(entry_id,url,role,form,label,context,PRIMARY KEY(entry_id,url));']
for e,t,tid,s in DATA:sql.append(f"INSERT INTO sm_e VALUES({e},{q(t)},{q('https://boardgamegeek.com/thread/'+tid if tid else None)},{q(s)});")
for row in R:sql.append('INSERT INTO sm_r VALUES('+','.join(q(v) for v in row)+');')
sql.append(f"UPDATE entries SET wip_thread_url=(SELECT wip FROM sm_e WHERE sm_e.id=entries.id) WHERE contest_id={CONTEST_ID};")
sql += [f"DELETE FROM entry_resource_scans WHERE entry_id IN (SELECT id FROM entries WHERE contest_id={CONTEST_ID}) AND checked_at='{DATE}';",f"INSERT INTO entry_resource_scans(entry_id,checked_at,source_url,wip_status,resource_listing_status,notes) SELECT id,'{DATE}',COALESCE(wip,'https://boardgamegeek.com/geeklist/353866/2025-solomode-design-contest-submissions'),CASE WHEN wip IS NULL THEN 'not_found' ELSE 'found' END,status,CASE WHEN status='not_observable' THEN 'Risorsa dichiarata ma non più osservabile dal primo post.' WHEN status='not_checked' THEN 'La voce GeekList punta alla pagina generale del contest; nessun WIP individuale inventato.' WHEN status='none_declared' THEN 'Primo post letto integralmente: nessun collegamento pertinente osservato.' ELSE 'Primo post renderizzato censito; destinazioni non aperte.' END FROM sm_e;","INSERT OR IGNORE INTO remote_resources(game_id,kind,access_type,url,host,label,availability_status,first_seen_at,last_verified_at) SELECT e.game_id,r.role,r.form,r.url,substr(r.url,instr(r.url,'//')+2,instr(substr(r.url,instr(r.url,'//')+2),'/')-1),r.label,'unknown','2026-09-15','2026-09-15' FROM sm_r r JOIN entries e ON e.id=r.entry_id;",f"DELETE FROM entry_resource_mentions WHERE entry_id IN (SELECT id FROM entries WHERE contest_id={CONTEST_ID});","INSERT INTO entry_resource_mentions(entry_id,remote_resource_id,source_url,label_raw,content_role,is_primary,first_seen_at,last_seen_at) SELECT r.entry_id,rr.id,s.wip,r.label,r.role,CASE WHEN r.role='game_files' THEN 1 ELSE 0 END,'2026-09-15','2026-09-15' FROM sm_r r JOIN sm_e s ON s.id=r.entry_id JOIN entries e ON e.id=r.entry_id JOIN remote_resources rr ON rr.game_id=e.game_id AND rr.url=r.url;","INSERT INTO remote_resource_observations(remote_resource_id,observed_at,evidence_url,observation_kind,availability_status,notes) SELECT rr.id,'2026-09-15',s.wip,'declared_in_wip','not_checked','Destinazione non aperta. Contesto: '||r.context FROM sm_r r JOIN sm_e s ON s.id=r.entry_id JOIN entries e ON e.id=r.entry_id JOIN remote_resources rr ON rr.game_id=e.game_id AND rr.url=r.url WHERE NOT EXISTS(SELECT 1 FROM remote_resource_observations o WHERE o.remote_resource_id=rr.id AND o.observed_at='2026-09-15');",'DROP TABLE sm_r;','DROP TABLE sm_e;','COMMIT;']
# Inserimento difensivo basato sulle risorse appena create: copre anche URL
# condivisi senza dipendere dalla ricomposizione della tabella temporanea.
sql.insert(-3,"INSERT OR IGNORE INTO entry_resource_mentions(entry_id,remote_resource_id,source_url,label_raw,content_role,is_primary,first_seen_at,last_seen_at) SELECT e.id,rr.id,e.wip_thread_url,rr.label,rr.kind,CASE WHEN rr.kind='game_files' THEN 1 ELSE 0 END,'2026-09-15','2026-09-15' FROM entries e JOIN remote_resources rr ON rr.game_id=e.game_id WHERE e.contest_id=16 AND rr.first_seen_at='2026-09-15';")
sql.insert(-3,"INSERT INTO remote_resource_observations(remote_resource_id,observed_at,evidence_url,observation_kind,availability_status,notes) SELECT rr.id,'2026-09-15',e.wip_thread_url,'declared_in_wip','not_checked','Destinazione non aperta. Contesto: '||COALESCE((SELECT r.context FROM sm_r r WHERE r.entry_id=e.id AND r.url=rr.url),'vedere registro versionato') FROM entries e JOIN remote_resources rr ON rr.game_id=e.game_id WHERE e.contest_id=16 AND rr.first_seen_at='2026-09-15' AND NOT EXISTS(SELECT 1 FROM remote_resource_observations o WHERE o.remote_resource_id=rr.id AND o.observed_at='2026-09-15');")
(ROOT/'catalog'/'2025-solomode-wips-resources.sql').write_text('\n'.join(sql)+'\n',encoding='utf-8')
c=Counter(e for e,*_ in R); labels={'observed':'risorse osservate','none_declared':'nessuna risorsa dichiarata','not_observable':'risorsa non osservabile','not_checked':'WIP non individuato'}
md=['# WIP e risorse dichiarate — Solomode 2025','','Verifica del 15 settembre 2026 sui primi post dei 36 WIP disponibili. Destinazioni non aperte. Le 38 proposte restano varianti dipendenti dal rispettivo gioco base.','','| # | Variante | Stato | Link |','|---:|---|---|---:|']
for i,(e,t,_,s) in enumerate(DATA,1):md.append(f'| {i} | {t} | {labels[s]} | {c[e]} |')
md+=['','## Risorse','','| Variante | Etichetta | Contesto | Funzione | Forma | Dominio | URL |','|---|---|---|---|---|---|---|'];titles={e:t for e,t,*_ in DATA};clean=lambda x:str(x).replace('|','/').replace('\n',' ')
for e,u,r,f,l,x in R:md.append(f'| {clean(titles[e])} | {clean(l)} | {clean(x)} | `{r}` | `{f}` | `{urlparse(u).netloc}` | {u} |')
md+=['','## Totali','',f'- 38 varianti: 36 WIP, 2 riferimenti generici senza WIP individuale.',f'- 34 WIP con risorse, 1 senza collegamenti pertinenti, 1 con risorsa rimossa/non osservabile.',f'- {len(R)} collegamenti distinti.','- Nessuna destinazione esterna aperta e nessun file scaricato.']
(ROOT/'sources'/'2025-SOLOMODE-WIPS-RESOURCES.md').write_text('\n'.join(md)+'\n',encoding='utf-8');print(len(R))
